# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class AnnsD(Base):
    """上市公司公告"""

    __tablename__: str = "anns_d"
    __api_id__: ClassVar[int] = 176
    __api_name__: ClassVar[str] = "anns_d"
    __api_title__: ClassVar[str] = "上市公司公告"
    __api_info_title__: ClassVar[str] = "上市公司公告"
    __api_path__: ClassVar[List[str]] = ["数据接口", "大模型语料专题数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 36]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["stock_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "ann_date", "title"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "ann_date": {"type": "String", "required": False, "description": "公告日期"},
        "start_date": {"type": "String", "required": False, "description": "公告开始日期"},
        "end_date": {"type": "String", "required": False, "description": "公告结束日期"},
        "title": {"type": "String", "required": False, "description": "标题"},
        "limit": {"type": "String", "required": False, "description": ""},
        "offset": {"type": "String", "required": False, "description": ""},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "上市公司公告",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ann_date = Column("ann_date", Date, nullable=False, comment="公告日期")
    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    name = Column("name", String(), nullable=True, comment="股票名称")
    title = Column("title", String(), nullable=False, comment="标题")
    url = Column("url", String(), nullable=True, comment="URL")
    rec_time = Column("rec_time", DateTime, nullable=True, comment="发布时间")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(AnnsD.__table__, "engine", engines.ReplacingMergeTree(order_by=AnnsD.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    AnnsD.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(AnnsD.__primary_key__),
            "order_by": ",".join(AnnsD.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    AnnsD.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": AnnsD.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    AnnsD.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": AnnsD.__primary_key__,
        }
    )
except Exception:
    pass
