# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class BakDaily(Base):
    """备用行情"""

    __tablename__: str = "bak_daily"
    __api_id__: ClassVar[int] = 255
    __api_name__: ClassVar[str] = "bak_daily"
    __api_title__: ClassVar[str] = "备用行情"
    __api_info_title__: ClassVar[str] = "备用行情"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 4]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "备用行情",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    name = Column("name", String(), nullable=True, comment="股票名称")
    pct_change = Column("pct_change", Float, nullable=True, comment="涨跌幅")
    close = Column("close", Float, nullable=True, comment="收盘价")
    change = Column("change", Float, nullable=True, comment="涨跌额")
    open = Column("open", Float, nullable=True, comment="开盘价")
    high = Column("high", Float, nullable=True, comment="最高价")
    low = Column("low", Float, nullable=True, comment="最低价")
    pre_close = Column("pre_close", Float, nullable=True, comment="昨收价")
    vol_ratio = Column("vol_ratio", Float, nullable=True, comment="量比")
    turn_over = Column("turn_over", Float, nullable=True, comment="换手率")
    swing = Column("swing", Float, nullable=True, comment="振幅")
    vol = Column("vol", Float, nullable=True, comment="成交量")
    amount = Column("amount", Float, nullable=True, comment="成交额")
    selling = Column("selling", Float, nullable=True, comment="内盘")
    buying = Column("buying", Float, nullable=True, comment="外盘")
    total_share = Column("total_share", Float, nullable=True, comment="总股本(万)")
    float_share = Column("float_share", Float, nullable=True, comment="流通股本(万)")
    pe = Column("pe", Float, nullable=True, comment="市盈(动)")
    industry = Column("industry", String(), nullable=True, comment="所属行业")
    area = Column("area", String(), nullable=True, comment="所属地域")
    float_mv = Column("float_mv", Float, nullable=True, comment="流通市值")
    total_mv = Column("total_mv", Float, nullable=True, comment="总市值")
    avg_price = Column("avg_price", Float, nullable=True, comment="平均价")
    strength = Column("strength", Float, nullable=True, comment="强弱度(%)")
    activity = Column("activity", Float, nullable=True, comment="活跃度(%)")
    avg_turnover = Column("avg_turnover", Float, nullable=True, comment="笔换手")
    attack = Column("attack", Float, nullable=True, comment="攻击波(%)")
    interval_3 = Column("interval_3", Float, nullable=True, comment="近3月涨幅")
    interval_6 = Column("interval_6", Float, nullable=True, comment="近6月涨幅")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(BakDaily.__table__, "engine", engines.ReplacingMergeTree(order_by=BakDaily.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    BakDaily.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(BakDaily.__primary_key__),
            "order_by": ",".join(BakDaily.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    BakDaily.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": BakDaily.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    BakDaily.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": BakDaily.__primary_key__,
        }
    )
except Exception:
    pass
