# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class BcOtcqt(Base):
    """柜台流通式债券报价"""

    __tablename__: str = "bc_otcqt"
    __api_id__: ClassVar[int] = 322
    __api_name__: ClassVar[str] = "bc_otcqt"
    __api_title__: ClassVar[str] = "柜台流通式债券报价"
    __api_info_title__: ClassVar[str] = "柜台流通式债券报价"
    __api_path__: ClassVar[List[str]] = ["数据接口", "债券专题"]
    __api_path_ids__: ClassVar[List[int]] = [1, 17]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": ""},
        "start_date": {"type": "String", "required": False, "description": ""},
        "end_date": {"type": "String", "required": False, "description": ""},
        "ts_code": {"type": "String", "required": False, "description": ""},
        "bank": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "柜台流通式债券报价",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="报价日期")
    qt_time = Column("qt_time", String(), nullable=True, comment="报价时间")
    bank = Column("bank", String(), nullable=True, comment="报价机构")
    ts_code = Column("ts_code", String(16), nullable=False, comment="债券编码")
    name = Column("name", String(), nullable=True, comment="债券简称")
    maturity = Column("maturity", String(), nullable=True, comment="期限")
    remain_maturity = Column("remain_maturity", String(), nullable=True, comment="剩余期限")
    bond_type = Column("bond_type", String(), nullable=True, comment="债券类型")
    coupon_rate = Column("coupon_rate", Float, nullable=True, comment="票面利率(%)")
    buy_price = Column("buy_price", Float, nullable=True, comment="投资者买入全价")
    sell_price = Column("sell_price", Float, nullable=True, comment="投资者卖出全价")
    buy_yield = Column("buy_yield", Float, nullable=True, comment="投资者买入到期收益率(%)")
    sell_yield = Column("sell_yield", Float, nullable=True, comment="投资者卖出到期收益率(%)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(BcOtcqt.__table__, "engine", engines.ReplacingMergeTree(order_by=BcOtcqt.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    BcOtcqt.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(BcOtcqt.__primary_key__),
            "order_by": ",".join(BcOtcqt.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    BcOtcqt.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": BcOtcqt.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    BcOtcqt.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": BcOtcqt.__primary_key__,
        }
    )
except Exception:
    pass
