# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class BoCinema(Base):
    """影院日度票房"""

    __tablename__: str = "bo_cinema"
    __api_id__: ClassVar[int] = 116
    __api_name__: ClassVar[str] = "bo_cinema"
    __api_title__: ClassVar[str] = "影院日度票房"
    __api_info_title__: ClassVar[str] = "影院日度票房"
    __api_path__: ClassVar[List[str]] = ["数据接口", "行业经济", "TMT行业"]
    __api_path_ids__: ClassVar[List[int]] = [1, 21, 22]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["date", "c_name"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "date": {"type": "String", "required": True, "description": "日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "影院日度票房",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    date = Column("date", Date, nullable=False, comment="日期")
    c_name = Column("c_name", String(), nullable=False, comment="影院名称")
    aud_count = Column("aud_count", Integer, nullable=True, comment="观众人数")
    att_ratio = Column("att_ratio", Float, nullable=True, comment="上座率")
    day_amount = Column("day_amount", Float, nullable=True, comment="当日票房")
    day_showcount = Column("day_showcount", Float, nullable=True, comment="当日场次")
    avg_price = Column("avg_price", Float, nullable=True, comment="场均票价(元)")
    p_pc = Column("p_pc", Float, nullable=True, comment="场均人次")
    rank = Column("rank", Integer, nullable=True, comment="排名")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(BoCinema.__table__, "engine", engines.ReplacingMergeTree(order_by=BoCinema.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    BoCinema.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(BoCinema.__primary_key__),
            "order_by": ",".join(BoCinema.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    BoCinema.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": BoCinema.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    BoCinema.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": BoCinema.__primary_key__,
        }
    )
except Exception:
    pass
