# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class BondBlk(Base):
    """大宗交易"""

    __tablename__: str = "bond_blk"
    __api_id__: ClassVar[int] = 271
    __api_name__: ClassVar[str] = "bond_blk"
    __api_title__: ClassVar[str] = "大宗交易"
    __api_info_title__: ClassVar[str] = "大宗交易"
    __api_path__: ClassVar[List[str]] = ["数据接口", "债券专题"]
    __api_path_ids__: ClassVar[List[int]] = [1, 17]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "债券代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "offset": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "String", "required": False, "description": ""},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "大宗交易",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    ts_code = Column("ts_code", String(16), nullable=False, comment="债券代码")
    name = Column("name", String(), nullable=True, comment="债券名称")
    price = Column("price", Float, nullable=True, comment="成交价(元)")
    vol = Column("vol", Float, nullable=True, comment="累计成交数量(万股/万份/万张/万手)")
    amount = Column("amount", Float, nullable=True, comment="累计成交金额(万元)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(BondBlk.__table__, "engine", engines.ReplacingMergeTree(order_by=BondBlk.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    BondBlk.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(BondBlk.__primary_key__),
            "order_by": ",".join(BondBlk.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    BondBlk.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": BondBlk.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    BondBlk.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": BondBlk.__primary_key__,
        }
    )
except Exception:
    pass
