# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class BrokerRecommend(Base):
    """券商月度金股"""

    __tablename__: str = "broker_recommend"
    __api_id__: ClassVar[int] = 267
    __api_name__: ClassVar[str] = "broker_recommend"
    __api_title__: ClassVar[str] = "券商月度金股"
    __api_info_title__: ClassVar[str] = "券商月度金股"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "特色数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 7]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["stock_basic"]
    __primary_key__: ClassVar[List[str]] = ["month", "broker", "ts_code"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "month": {"type": "String", "required": True, "description": "月度（YYYYMM）"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "券商月度金股",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    month = Column("month", String(), nullable=False, comment="月度")
    broker = Column("broker", String(), nullable=False, comment="券商")
    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    name = Column("name", String(), nullable=True, comment="股票简称")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(BrokerRecommend.__table__, "engine", engines.ReplacingMergeTree(order_by=BrokerRecommend.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    BrokerRecommend.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(BrokerRecommend.__primary_key__),
            "order_by": ",".join(BrokerRecommend.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    BrokerRecommend.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": BrokerRecommend.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    BrokerRecommend.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": BrokerRecommend.__primary_key__,
        }
    )
except Exception:
    pass
