# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class BseMapping(Base):
    """北交所新旧代码对照"""

    __tablename__: str = "bse_mapping"
    __api_id__: ClassVar[int] = 375
    __api_name__: ClassVar[str] = "bse_mapping"
    __api_title__: ClassVar[str] = "北交所新旧代码对照"
    __api_info_title__: ClassVar[str] = "北交所新旧代码对照"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "基础数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 3]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["o_code"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "o_code": {"type": "String", "required": False, "description": "旧代码"},
        "n_code": {"type": "String", "required": False, "description": "新代码"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "北交所新旧代码对照",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    name = Column("name", String(), nullable=True, comment="股票代码")
    o_code = Column("o_code", String(), nullable=False, comment="原代码")
    n_code = Column("n_code", String(), nullable=True, comment="新代码")
    list_date = Column("list_date", Date, nullable=True, comment="上市日期")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(BseMapping.__table__, "engine", engines.ReplacingMergeTree(order_by=BseMapping.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    BseMapping.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(BseMapping.__primary_key__),
            "order_by": ",".join(BseMapping.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    BseMapping.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": BseMapping.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    BseMapping.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": BseMapping.__primary_key__,
        }
    )
except Exception:
    pass
