# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class BtcPricevol(Base):
    """比特币每日量价"""

    __tablename__: str = "btc_pricevol"
    __api_id__: ClassVar[int] = 77
    __api_name__: ClassVar[str] = "btc_pricevol"
    __api_title__: ClassVar[str] = "比特币每日量价"
    __api_info_title__: ClassVar[str] = "比特币每日量价"
    __api_path__: ClassVar[List[str]] = ["另类数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [37, 39]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["coinlist"]
    __primary_key__: ClassVar[List[str]] = ["date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "start_date": {"type": "String", "required": True, "description": "开始时间"},
        "end_date": {"type": "String", "required": True, "description": "结束时间"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "比特币每日量价",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    date = Column("date", Date, nullable=False, comment="日期")
    price = Column("price", Float, nullable=True, comment="价格")
    volume = Column("volume", Float, nullable=True, comment="交易量")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(BtcPricevol.__table__, "engine", engines.ReplacingMergeTree(order_by=BtcPricevol.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    BtcPricevol.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(BtcPricevol.__primary_key__),
            "order_by": ",".join(BtcPricevol.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    BtcPricevol.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": BtcPricevol.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    BtcPricevol.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": BtcPricevol.__primary_key__,
        }
    )
except Exception:
    pass
