# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class CbRate(Base):
    """可转债票面利率"""

    __tablename__: str = "cb_rate"
    __api_id__: ClassVar[int] = 305
    __api_name__: ClassVar[str] = "cb_rate"
    __api_title__: ClassVar[str] = "可转债票面利率"
    __api_info_title__: ClassVar[str] = "可转债票面利率"
    __api_path__: ClassVar[List[str]] = ["数据接口", "债券专题"]
    __api_path_ids__: ClassVar[List[int]] = [1, 17]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["cb_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "rate_start_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "转债代码，支持多值输入"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "可转债票面利率",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="转债代码")
    rate_freq = Column("rate_freq", Integer, nullable=True, comment="付息频率(次/年)")
    rate_start_date = Column("rate_start_date", Date, nullable=False, comment="纯债价值")
    rate_end_date = Column("rate_end_date", Date, nullable=True, comment="纯债溢价率(%)")
    coupon_rate = Column("coupon_rate", Float, nullable=True, comment="票面利率(%)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(CbRate.__table__, "engine", engines.ReplacingMergeTree(order_by=CbRate.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    CbRate.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(CbRate.__primary_key__),
            "order_by": ",".join(CbRate.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    CbRate.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": CbRate.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    CbRate.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": CbRate.__primary_key__,
        }
    )
except Exception:
    pass
