# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class CnGdp(Base):
    """国内生产总值(GDP)"""

    __tablename__: str = "cn_gdp"
    __api_id__: ClassVar[int] = 227
    __api_name__: ClassVar[str] = "cn_gdp"
    __api_title__: ClassVar[str] = "国内生产总值(GDP)"
    __api_info_title__: ClassVar[str] = "国内生产总值(GDP)"
    __api_path__: ClassVar[List[str]] = ["数据接口", "宏观经济", "国内宏观", "国民经济"]
    __api_path_ids__: ClassVar[List[int]] = [1, 23, 24, 26]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["quarter"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "q": {"type": "String", "required": False, "description": "季度"},
        "start_q": {"type": "String", "required": False, "description": "开始季度"},
        "end_q": {"type": "String", "required": False, "description": "结束季度"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "国内生产总值(GDP)",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    quarter = Column("quarter", String(), nullable=False, comment="季度")
    gdp = Column("gdp", Float, nullable=True, comment="GDP累计值(亿元)")
    gdp_yoy = Column("gdp_yoy", Float, nullable=True, comment="当季同比增速(%)")
    pi = Column("pi", Float, nullable=True, comment="第一产业累计值(亿元)")
    pi_yoy = Column("pi_yoy", Float, nullable=True, comment="第一产业同比增速(%)")
    si = Column("si", Float, nullable=True, comment="第二产业累计值(亿元)")
    si_yoy = Column("si_yoy", Float, nullable=True, comment="第二产业同比增速(%)")
    ti = Column("ti", Float, nullable=True, comment="第三产业累计值(亿元)")
    ti_yoy = Column("ti_yoy", Float, nullable=True, comment="第三产业同比增速(%)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(CnGdp.__table__, "engine", engines.ReplacingMergeTree(order_by=CnGdp.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    CnGdp.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(CnGdp.__primary_key__),
            "order_by": ",".join(CnGdp.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    CnGdp.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": CnGdp.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    CnGdp.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": CnGdp.__primary_key__,
        }
    )
except Exception:
    pass
