# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class Coinlist(Base):
    """全球数字货币列表"""

    __tablename__: str = "coinlist"
    __api_id__: ClassVar[int] = 54
    __api_name__: ClassVar[str] = "coinlist"
    __api_title__: ClassVar[str] = "全球数字货币列表"
    __api_info_title__: ClassVar[str] = "全球数字货币列表"
    __api_path__: ClassVar[List[str]] = ["另类数据", "基础数据"]
    __api_path_ids__: ClassVar[List[int]] = [37, 38]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["coin"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "issue_date": {"type": "String", "required": False, "description": "发行日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "全球数字货币列表",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    coin = Column("coin", String(), nullable=False, comment="货币代码")
    en_name = Column("en_name", String(), nullable=True, comment="英文名称")
    cn_name = Column("cn_name", String(), nullable=True, comment="中文名称")
    issue_date = Column("issue_date", Date, nullable=True, comment="发行日期")
    issue_price = Column("issue_price", Float, nullable=True, comment="发行价格(美元)")
    amount = Column("amount", Float, nullable=True, comment="发行总量")
    supply = Column("supply", Float, nullable=True, comment="流通总量")
    algo = Column("algo", String(), nullable=True, comment="算法原理")
    area = Column("area", String(), nullable=True, comment="发行地区")
    desc = Column("desc", String(), nullable=True, comment="描述")
    labels = Column("labels", String(), nullable=True, comment="标签分类")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(Coinlist.__table__, "engine", engines.ReplacingMergeTree(order_by=Coinlist.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    Coinlist.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(Coinlist.__primary_key__),
            "order_by": ",".join(Coinlist.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    Coinlist.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": Coinlist.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    Coinlist.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": Coinlist.__primary_key__,
        }
    )
except Exception:
    pass
