# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class Coinfees(Base):
    """交易所交易费率"""

    __tablename__: str = "coinfees"
    __api_id__: ClassVar[int] = 64
    __api_name__: ClassVar[str] = "coinfees"
    __api_title__: ClassVar[str] = "交易所交易费率"
    __api_info_title__: ClassVar[str] = "交易所交易费率"
    __api_path__: ClassVar[List[str]] = ["另类数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [37, 39]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["exchange", "asset_type", "start_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "exchange": {"type": "String", "required": True, "description": "交易所"},
        "asset_type": {"type": "String", "required": False, "description": "交易类别coin币交易 future期货交易"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "交易所交易费率",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    exchange = Column("exchange", String(), nullable=False, comment="交易所")
    level = Column("level", String(), nullable=True, comment="交易级别和类型")
    maker_fee = Column("maker_fee", Float, nullable=True, comment="挂单费率")
    taker_fee = Column("taker_fee", Float, nullable=True, comment="吃单费率")
    asset_type = Column("asset_type", String(), nullable=False, comment="资产类别 coin币交易 future期货交易")
    start_date = Column("start_date", Date, nullable=False, comment="费率开始执行日期")
    end_date = Column("end_date", Date, nullable=True, comment="本次费率失效日期")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(Coinfees.__table__, "engine", engines.ReplacingMergeTree(order_by=Coinfees.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    Coinfees.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(Coinfees.__primary_key__),
            "order_by": ",".join(Coinfees.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    Coinfees.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": Coinfees.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    Coinfees.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": Coinfees.__primary_key__,
        }
    )
except Exception:
    pass
