# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class CoinBar(Base):
    """数字货币k线行情"""

    __tablename__: str = "coin_bar"
    __api_id__: ClassVar[int] = 238
    __api_name__: ClassVar[str] = "coin_bar"
    __api_title__: ClassVar[str] = "数字货币k线行情"
    __api_info_title__: ClassVar[str] = "数字货币k线行情"
    __api_path__: ClassVar[List[str]] = ["另类数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [37, 39]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["coinexchanges", "coin_pair"]
    __primary_key__: ClassVar[List[str]] = ["exchange", "ts_code", "freq", "trade_time"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "代码"},
        "symbol": {"type": "String", "required": False, "description": "交易所原始代码"},
        "exchange": {"type": "String", "required": False, "description": "交易所"},
        "freq": {"type": "String", "required": False, "description": "频度"},
        "start_date": {"type": "Datetime", "required": False, "description": "开始日期"},
        "end_date": {"type": "Datetime", "required": False, "description": "结束日期"},
        "is_contract": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "数字货币k线行情",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    exchange = Column("exchange", String(), nullable=False, comment="交易所")
    ts_code = Column("ts_code", String(16), nullable=False, comment="TS代码")
    symbol = Column("symbol", String(), nullable=True, comment="交易所原始代码")
    freq = Column("freq", String(), nullable=False, comment="频度")
    trade_time = Column("trade_time", String(), nullable=False, comment="交易时间")
    open = Column("open", Float, nullable=True, comment="开盘价")
    close = Column("close", Float, nullable=True, comment="收盘价")
    high = Column("high", Float, nullable=True, comment="最高价")
    low = Column("low", Float, nullable=True, comment="最低价")
    vol = Column("vol", Float, nullable=True, comment="成交量")
    is_contract = Column("is_contract", String(), nullable=True, comment="是否合约")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(CoinBar.__table__, "engine", engines.ReplacingMergeTree(order_by=CoinBar.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    CoinBar.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(CoinBar.__primary_key__),
            "order_by": ",".join(CoinBar.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    CoinBar.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": CoinBar.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    CoinBar.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": CoinBar.__primary_key__,
        }
    )
except Exception:
    pass
