# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class Coinpair(Base):
    """交易所交易对"""

    __tablename__: str = "coinpair"
    __api_id__: ClassVar[int] = 51
    __api_name__: ClassVar[str] = "coinpair"
    __api_title__: ClassVar[str] = "交易所交易对"
    __api_info_title__: ClassVar[str] = "交易所交易对"
    __api_path__: ClassVar[List[str]] = ["另类数据", "基础数据"]
    __api_path_ids__: ClassVar[List[int]] = [37, 38]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["coinexchanges", "coinlist"]
    __primary_key__: ClassVar[List[str]] = ["trade_date", "exchange", "exchange_pair"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "日期"},
        "exchange": {"type": "String", "required": True, "description": "交易所"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "交易所交易对",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="日期")
    exchange = Column("exchange", String(), nullable=False, comment="交易所")
    exchange_pair = Column("exchange_pair", String(), nullable=False, comment="交易所原始交易对名称")
    ts_pair = Column("ts_pair", String(), nullable=True, comment="Tushare标准名称")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(Coinpair.__table__, "engine", engines.ReplacingMergeTree(order_by=Coinpair.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    Coinpair.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(Coinpair.__primary_key__),
            "order_by": ",".join(Coinpair.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    Coinpair.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": Coinpair.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    Coinpair.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": Coinpair.__primary_key__,
        }
    )
except Exception:
    pass
