# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class Coincap(Base):
    """数字货币每日市值"""

    __tablename__: str = "coincap"
    __api_id__: ClassVar[int] = 57
    __api_name__: ClassVar[str] = "coincap"
    __api_title__: ClassVar[str] = "数字货币每日市值"
    __api_info_title__: ClassVar[str] = "数字货币每日市值"
    __api_path__: ClassVar[List[str]] = ["另类数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [37, 39]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["coinlist"]
    __primary_key__: ClassVar[List[str]] = ["trade_date", "coin"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": True, "description": "日期"},
        "coin": {"type": "String", "required": False, "description": "coin代码"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "数字货币每日市值",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    coin = Column("coin", String(), nullable=False, comment="货币代码")
    name = Column("name", String(), nullable=True, comment="货币名称")
    marketcap = Column("marketcap", String(), nullable=True, comment="市值(美元)")
    price = Column("price", Float, nullable=True, comment="当前时间价格(美元)")
    vol24 = Column("vol24", Float, nullable=True, comment="24小时成交额(美元)")
    supply = Column("supply", Float, nullable=True, comment="流通总量")
    create_time = Column("create_time", String(), nullable=True, comment="数据采集时间")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(Coincap.__table__, "engine", engines.ReplacingMergeTree(order_by=Coincap.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    Coincap.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(Coincap.__primary_key__),
            "order_by": ",".join(Coincap.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    Coincap.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": Coincap.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    Coincap.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": Coincap.__primary_key__,
        }
    )
except Exception:
    pass
