# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class CoinPair(Base):
    """交易所交易对(新)"""

    __tablename__: str = "coin_pair"
    __api_id__: ClassVar[int] = 258
    __api_name__: ClassVar[str] = "coin_pair"
    __api_title__: ClassVar[str] = "交易所交易对(新)"
    __api_info_title__: ClassVar[str] = "交易所交易对(新)"
    __api_path__: ClassVar[List[str]] = ["另类数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [37, 39]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["exchange", "symbol"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "exchange": {"type": "String", "required": False, "description": "交易所"},
        "ts_code": {"type": "String", "required": False, "description": "交易对代码"},
        "status": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "交易所交易对(新)",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    exchange = Column("exchange", String(), nullable=False, comment="交易所")
    symbol = Column("symbol", String(), nullable=False, comment="交易对")
    is_contract = Column("is_contract", String(), nullable=True, comment="是否合约")
    status = Column("status", String(), nullable=True, comment="状态Y可用N不可用")
    base_coin = Column("base_coin", String(), nullable=True, comment="")
    price_coin = Column("price_coin", String(), nullable=True, comment="")
    listing = Column("listing", DateTime, nullable=True, comment="")
    delivery = Column("delivery", DateTime, nullable=True, comment="")
    create_time = Column("create_time", DateTime, nullable=True, comment="")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(CoinPair.__table__, "engine", engines.ReplacingMergeTree(order_by=CoinPair.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    CoinPair.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(CoinPair.__primary_key__),
            "order_by": ",".join(CoinPair.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    CoinPair.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": CoinPair.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    CoinPair.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": CoinPair.__primary_key__,
        }
    )
except Exception:
    pass
