# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class CyqPerf(Base):
    """每日筹码及胜率"""

    __tablename__: str = "cyq_perf"
    __api_id__: ClassVar[int] = 293
    __api_name__: ClassVar[str] = "cyq_perf"
    __api_title__: ClassVar[str] = "每日筹码及胜率"
    __api_info_title__: ClassVar[str] = "每日筹码及胜率"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "特色数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 7]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期（YYYYMMDD）"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "每日筹码及胜率",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    his_low = Column("his_low", Float, nullable=True, comment="历史最低价")
    his_high = Column("his_high", Float, nullable=True, comment="历史最高价")
    cost_5pct = Column("cost_5pct", Float, nullable=True, comment="5分位成本")
    cost_15pct = Column("cost_15pct", Float, nullable=True, comment="15分位成本")
    cost_50pct = Column("cost_50pct", Float, nullable=True, comment="50分位成本")
    cost_85pct = Column("cost_85pct", Float, nullable=True, comment="85分位成本")
    cost_95pct = Column("cost_95pct", Float, nullable=True, comment="95分位成本")
    weight_avg = Column("weight_avg", Float, nullable=True, comment="加权平均成本")
    winner_rate = Column("winner_rate", Float, nullable=True, comment="胜率")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(CyqPerf.__table__, "engine", engines.ReplacingMergeTree(order_by=CyqPerf.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    CyqPerf.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(CyqPerf.__primary_key__),
            "order_by": ",".join(CyqPerf.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    CyqPerf.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": CyqPerf.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    CyqPerf.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": CyqPerf.__primary_key__,
        }
    )
except Exception:
    pass
