# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class DailyInfo(Base):
    """沪深市场每日交易统计"""

    __tablename__: str = "daily_info"
    __api_id__: ClassVar[int] = 215
    __api_name__: ClassVar[str] = "daily_info"
    __api_title__: ClassVar[str] = "沪深市场每日交易统计"
    __api_info_title__: ClassVar[str] = "沪深市场每日交易统计"
    __api_path__: ClassVar[List[str]] = ["数据接口", "指数专题"]
    __api_path_ids__: ClassVar[List[int]] = [1, 12]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "ts_code": {"type": "String", "required": False, "description": "板块代码"},
        "exchange": {"type": "String", "required": False, "description": "股票市场"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "沪深市场每日交易统计",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    ts_code = Column("ts_code", String(16), nullable=False, comment="市场代码")
    ts_name = Column("ts_name", String(), nullable=True, comment="市场名称")
    com_count = Column("com_count", Integer, nullable=True, comment="挂牌数")
    total_share = Column("total_share", Float, nullable=True, comment="总股本(亿股)")
    float_share = Column("float_share", Float, nullable=True, comment="流通股本(亿股)")
    total_mv = Column("total_mv", Float, nullable=True, comment="总市值(亿元)")
    float_mv = Column("float_mv", Float, nullable=True, comment="流通市值(亿元)")
    amount = Column("amount", Float, nullable=True, comment="交易金额(亿元)")
    vol = Column("vol", Float, nullable=True, comment="成交量(亿股)")
    trans_count = Column("trans_count", Integer, nullable=True, comment="成交笔数(万笔)")
    pe = Column("pe", Float, nullable=True, comment="平均市盈率")
    tr = Column("tr", Float, nullable=True, comment="换手率(％)")
    exchange = Column("exchange", String(), nullable=True, comment="交易所")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(DailyInfo.__table__, "engine", engines.ReplacingMergeTree(order_by=DailyInfo.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    DailyInfo.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(DailyInfo.__primary_key__),
            "order_by": ",".join(DailyInfo.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    DailyInfo.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": DailyInfo.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    DailyInfo.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": DailyInfo.__primary_key__,
        }
    )
except Exception:
    pass
