# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class DcMember(Base):
    """东方财富概念成分"""

    __tablename__: str = "dc_member"
    __api_id__: ClassVar[int] = 363
    __api_name__: ClassVar[str] = "dc_member"
    __api_title__: ClassVar[str] = "东方财富概念成分"
    __api_info_title__: ClassVar[str] = "东方财富概念成分"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "打板专题数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 10]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal", "dc_index"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "交易日期（YYYYMMDD格式）"},
        "ts_code": {"type": "String", "required": False, "description": "板块指数代码"},
        "con_code": {"type": "String", "required": False, "description": "成分股票代码"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "东方财富概念成分",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    ts_code = Column("ts_code", String(16), nullable=False, comment="概念代码")
    con_code = Column("con_code", String(), nullable=True, comment="成分代码")
    name = Column("name", String(), nullable=True, comment="成分股名称")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(DcMember.__table__, "engine", engines.ReplacingMergeTree(order_by=DcMember.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    DcMember.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(DcMember.__primary_key__),
            "order_by": ",".join(DcMember.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    DcMember.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": DcMember.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    DcMember.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": DcMember.__primary_key__,
        }
    )
except Exception:
    pass
