# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class DisclosureDate(Base):
    """财报披露日期表"""

    __tablename__: str = "disclosure_date"
    __api_id__: ClassVar[int] = 162
    __api_name__: ClassVar[str] = "disclosure_date"
    __api_title__: ClassVar[str] = "财报披露日期表"
    __api_info_title__: ClassVar[str] = "财报披露日期表"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "财务数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 5]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code", "end_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "TS股票代码"},
        "end_date": {"type": "String", "required": False, "description": "财报周期"},
        "pre_date": {"type": "String", "required": False, "description": "计划披露日期"},
        "ann_date": {"type": "String", "required": False, "description": "最新披露公告日"},
        "actual_date": {"type": "String", "required": False, "description": "实际披露日期"},
        "offset": {"type": "Int64", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": ""},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "财报披露日期表",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="TS代码")
    ann_date = Column("ann_date", Date, nullable=True, comment="最新披露公告日")
    end_date = Column("end_date", Date, nullable=False, comment="报告期")
    pre_date = Column("pre_date", Date, nullable=True, comment="预计披露日期")
    actual_date = Column("actual_date", Date, nullable=True, comment="实际披露日期")
    modify_date = Column("modify_date", Date, nullable=True, comment="披露日期修正记录")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(DisclosureDate.__table__, "engine", engines.ReplacingMergeTree(order_by=DisclosureDate.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    DisclosureDate.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(DisclosureDate.__primary_key__),
            "order_by": ",".join(DisclosureDate.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    DisclosureDate.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": DisclosureDate.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    DisclosureDate.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": DisclosureDate.__primary_key__,
        }
    )
except Exception:
    pass
