# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class EtfBasic(Base):
    """ETF基本信息"""

    __tablename__: str = "etf_basic"
    __api_id__: ClassVar[int] = 385
    __api_name__: ClassVar[str] = "etf_basic"
    __api_title__: ClassVar[str] = "ETF基本信息"
    __api_info_title__: ClassVar[str] = "ETF基本信息"
    __api_path__: ClassVar[List[str]] = ["数据接口", "ETF专题"]
    __api_path_ids__: ClassVar[List[int]] = [1, 11]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "ETF代码"},
        "index_code": {"type": "String", "required": False, "description": "跟踪指数代码"},
        "list_date": {"type": "String", "required": False, "description": "上市日期"},
        "list_status": {"type": "String", "required": False, "description": "上市状态"},
        "exchange": {"type": "String", "required": False, "description": "交易所：SH上交所 SZ深交所"},
        "mgr": {"type": "String", "required": False, "description": "管理人（简称，e.g.华夏基金)"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "ETF基本信息",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="基金交易代码")
    csname = Column("csname", String(), nullable=True, comment="ETF中文简称")
    extname = Column("extname", String(), nullable=True, comment="ETF扩位简称(对应交易所简称)")
    cname = Column("cname", String(), nullable=True, comment="基金中文全称")
    index_code = Column("index_code", String(), nullable=True, comment="ETF基准指数代码")
    index_name = Column("index_name", String(), nullable=True, comment="ETF基准指数中文全称")
    setup_date = Column("setup_date", Date, nullable=True, comment="基金设立日期")
    list_date = Column("list_date", Date, nullable=True, comment="基金上市日期")
    list_status = Column("list_status", String(), nullable=True, comment="基金存续状态L上市 D退市 P待上市")
    exchange = Column("exchange", String(), nullable=True, comment="交易所编码上交所SH 深交所SZ")
    mgr_name = Column("mgr_name", String(), nullable=True, comment="基金管理人简称")
    custod_name = Column("custod_name", String(), nullable=True, comment="基金托管人名称")
    mgt_fee = Column("mgt_fee", Float, nullable=True, comment="基金管理人收取的费用")
    etf_type = Column("etf_type", String(), nullable=True, comment="基金投资通道类型(境内、QDII)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(EtfBasic.__table__, "engine", engines.ReplacingMergeTree(order_by=EtfBasic.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    EtfBasic.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(EtfBasic.__primary_key__),
            "order_by": ",".join(EtfBasic.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    EtfBasic.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": EtfBasic.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    EtfBasic.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": EtfBasic.__primary_key__,
        }
    )
except Exception:
    pass
