# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FinaMainbz(Base):
    """主营业务构成"""

    __tablename__: str = "fina_mainbz"
    __api_id__: ClassVar[int] = 81
    __api_name__: ClassVar[str] = "fina_mainbz"
    __api_title__: ClassVar[str] = "主营业务构成"
    __api_info_title__: ClassVar[str] = "主营业务构成"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "财务数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 5]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code", "end_date", "bz_item"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": True, "description": "股票代码"},
        "period": {"type": "String", "required": False, "description": "报告期"},
        "type": {"type": "String", "required": False, "description": "类型：P按产品 D按地区"},
        "start_date": {"type": "String", "required": False, "description": "报告期开始日期"},
        "end_date": {"type": "String", "required": False, "description": "报告期结束日期"},
        "is_publish": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "主营业务构成",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="TS代码")
    end_date = Column("end_date", Date, nullable=False, comment="报告期")
    bz_item = Column("bz_item", String(), nullable=False, comment="主营业务项目")
    bz_code = Column("bz_code", String(), nullable=True, comment="项目代码")
    bz_sales = Column("bz_sales", Float, nullable=True, comment="主营业务收入(元)")
    bz_profit = Column("bz_profit", Float, nullable=True, comment="主营业务利润(元)")
    bz_cost = Column("bz_cost", Float, nullable=True, comment="主营业务成本(元)")
    curr_type = Column("curr_type", String(), nullable=True, comment="货币代码")
    update_flag = Column("update_flag", Date, nullable=True, comment="是否更新")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FinaMainbz.__table__, "engine", engines.ReplacingMergeTree(order_by=FinaMainbz.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FinaMainbz.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FinaMainbz.__primary_key__),
            "order_by": ",".join(FinaMainbz.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FinaMainbz.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FinaMainbz.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FinaMainbz.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FinaMainbz.__primary_key__,
        }
    )
except Exception:
    pass
