# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FtLimit(Base):
    """期货合约涨跌停价格"""

    __tablename__: str = "ft_limit"
    __api_id__: ClassVar[int] = 368
    __api_name__: ClassVar[str] = "ft_limit"
    __api_title__: ClassVar[str] = "期货合约涨跌停价格"
    __api_info_title__: ClassVar[str] = "期货合约涨跌停价格"
    __api_path__: ClassVar[List[str]] = ["数据接口", "期货数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 14]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal", "fut_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "合约代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "cont": {"type": "String", "required": False, "description": "合约代码（例如：cont='CU')"},
        "exchange": {"type": "String", "required": False, "description": "交易所代码"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "期货合约涨跌停价格",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    ts_code = Column("ts_code", String(16), nullable=False, comment="TS股票代码")
    name = Column("name", String(), nullable=True, comment="合约名称")
    up_limit = Column("up_limit", Float, nullable=True, comment="涨停价")
    down_limit = Column("down_limit", Float, nullable=True, comment="跌停价")
    m_ratio = Column("m_ratio", Float, nullable=True, comment="最低交易保证金率")
    cont = Column("cont", String(), nullable=True, comment="合约代码")
    exchange = Column("exchange", String(), nullable=True, comment="交易所代码")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FtLimit.__table__, "engine", engines.ReplacingMergeTree(order_by=FtLimit.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FtLimit.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FtLimit.__primary_key__),
            "order_by": ",".join(FtLimit.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FtLimit.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FtLimit.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FtLimit.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FtLimit.__primary_key__,
        }
    )
except Exception:
    pass
