# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FundSalesVol(Base):
    """销售机构公募基金销售保有规模"""

    __tablename__: str = "fund_sales_vol"
    __api_id__: ClassVar[int] = 266
    __api_name__: ClassVar[str] = "fund_sales_vol"
    __api_title__: ClassVar[str] = "销售机构公募基金销售保有规模"
    __api_info_title__: ClassVar[str] = "销售机构公募基金销售保有规模"
    __api_path__: ClassVar[List[str]] = ["数据接口", "财富管理", "基金销售行业数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 34, 35]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["year", "quarter", "inst_name"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "year": {"type": "String", "required": False, "description": "年度"},
        "quarter": {"type": "String", "required": False, "description": "季度"},
        "name": {"type": "String", "required": False, "description": "机构名称"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "销售机构公募基金销售保有规模",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    year = Column("year", Integer, nullable=False, comment="年度")
    quarter = Column("quarter", String(), nullable=False, comment="季度")
    inst_name = Column("inst_name", String(), nullable=False, comment="销售机构")
    fund_scale = Column("fund_scale", Float, nullable=True, comment="股票+混合公募基金保有规模(亿元)")
    scale = Column("scale", Float, nullable=True, comment="非货币市场公募基金保有规模(亿元)")
    rank = Column("rank", Integer, nullable=True, comment="排名")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FundSalesVol.__table__, "engine", engines.ReplacingMergeTree(order_by=FundSalesVol.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FundSalesVol.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FundSalesVol.__primary_key__),
            "order_by": ",".join(FundSalesVol.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FundSalesVol.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FundSalesVol.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FundSalesVol.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FundSalesVol.__primary_key__,
        }
    )
except Exception:
    pass
