# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FundShare(Base):
    """基金规模"""

    __tablename__: str = "fund_share"
    __api_id__: ClassVar[int] = 207
    __api_name__: ClassVar[str] = "fund_share"
    __api_title__: ClassVar[str] = "基金规模"
    __api_info_title__: ClassVar[str] = "基金规模"
    __api_path__: ClassVar[List[str]] = ["数据接口", "公募基金"]
    __api_path_ids__: ClassVar[List[int]] = [1, 13]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal", "fund_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "TS基金代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "market": {"type": "String", "required": False, "description": "市场：SH/SZ"},
        "fund_type": {"type": "String", "required": False, "description": "类型"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "基金规模",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="基金代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易(变动)日期")
    fd_share = Column("fd_share", Float, nullable=True, comment="基金份额(万)")
    total_share = Column("total_share", Float, nullable=True, comment="合计份额(万)")
    fund_type = Column("fund_type", String(), nullable=True, comment="基金类型")
    market = Column("market", String(), nullable=True, comment="市场")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FundShare.__table__, "engine", engines.ReplacingMergeTree(order_by=FundShare.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FundShare.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FundShare.__primary_key__),
            "order_by": ",".join(FundShare.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FundShare.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FundShare.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FundShare.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FundShare.__primary_key__,
        }
    )
except Exception:
    pass
