# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FundPortfolio(Base):
    """基金持仓"""

    __tablename__: str = "fund_portfolio"
    __api_id__: ClassVar[int] = 121
    __api_name__: ClassVar[str] = "fund_portfolio"
    __api_title__: ClassVar[str] = "基金持仓"
    __api_info_title__: ClassVar[str] = "基金持仓"
    __api_path__: ClassVar[List[str]] = ["数据接口", "公募基金"]
    __api_path_ids__: ClassVar[List[int]] = [1, 13]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["fund_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "ann_date", "end_date", "symbol"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "基金代码"},
        "ann_date": {"type": "String", "required": False, "description": "公告日期"},
        "start_date": {"type": "String", "required": False, "description": "公告开始日期"},
        "end_date": {"type": "String", "required": False, "description": "公告结束日期"},
        "period": {"type": "String", "required": False, "description": "报告期"},
        "symbol": {"type": "String", "required": False, "description": "股票代码"},
        "offset": {"type": "Int64", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "基金持仓",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="TS基金代码")
    ann_date = Column("ann_date", Date, nullable=False, comment="公告日期")
    end_date = Column("end_date", Date, nullable=False, comment="截止日期")
    symbol = Column("symbol", String(), nullable=False, comment="股票代码")
    mkv = Column("mkv", Float, nullable=True, comment="持有股票市值(元)")
    amount = Column("amount", Float, nullable=True, comment="持有股票数量(股)")
    stk_mkv_ratio = Column("stk_mkv_ratio", Float, nullable=True, comment="占股票市值比")
    stk_float_ratio = Column("stk_float_ratio", Float, nullable=True, comment="占流通股本比例")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FundPortfolio.__table__, "engine", engines.ReplacingMergeTree(order_by=FundPortfolio.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FundPortfolio.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FundPortfolio.__primary_key__),
            "order_by": ",".join(FundPortfolio.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FundPortfolio.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FundPortfolio.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FundPortfolio.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FundPortfolio.__primary_key__,
        }
    )
except Exception:
    pass
