# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FutSettle(Base):
    """每日结算参数"""

    __tablename__: str = "fut_settle"
    __api_id__: ClassVar[int] = 141
    __api_name__: ClassVar[str] = "fut_settle"
    __api_title__: ClassVar[str] = "每日结算参数"
    __api_info_title__: ClassVar[str] = "每日结算参数"
    __api_path__: ClassVar[List[str]] = ["数据接口", "期货数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 14]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal", "fut_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "ts_code": {"type": "String", "required": False, "description": "合约代码"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "exchange": {"type": "String", "required": False, "description": "交易所代码"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "每日结算参数",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="合约代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    settle = Column("settle", Float, nullable=True, comment="结算价")
    trading_fee_rate = Column("trading_fee_rate", Float, nullable=True, comment="交易手续费率")
    trading_fee = Column("trading_fee", Float, nullable=True, comment="交易手续费")
    delivery_fee = Column("delivery_fee", Float, nullable=True, comment="交割手续费")
    b_hedging_margin_rate = Column("b_hedging_margin_rate", Float, nullable=True, comment="买套保交易保证金率")
    s_hedging_margin_rate = Column("s_hedging_margin_rate", Float, nullable=True, comment="卖套保交易保证金率")
    long_margin_rate = Column("long_margin_rate", Float, nullable=True, comment="买投机交易保证金率")
    short_margin_rate = Column("short_margin_rate", Float, nullable=True, comment="卖投机交易保证金率")
    offset_today_fee = Column("offset_today_fee", Float, nullable=True, comment="平今仓手续率")
    exchange = Column("exchange", String(), nullable=True, comment="交易所")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FutSettle.__table__, "engine", engines.ReplacingMergeTree(order_by=FutSettle.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FutSettle.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FutSettle.__primary_key__),
            "order_by": ",".join(FutSettle.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FutSettle.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FutSettle.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FutSettle.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FutSettle.__primary_key__,
        }
    )
except Exception:
    pass
