# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FutWeeklyDetail(Base):
    """期货主要品种交易周报"""

    __tablename__: str = "fut_weekly_detail"
    __api_id__: ClassVar[int] = 216
    __api_name__: ClassVar[str] = "fut_weekly_detail"
    __api_title__: ClassVar[str] = "期货主要品种交易周报"
    __api_info_title__: ClassVar[str] = "期货主要品种交易周报"
    __api_path__: ClassVar[List[str]] = ["数据接口", "期货数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 14]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["exchange", "prd", "week"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "week": {"type": "String", "required": False, "description": "周期"},
        "prd": {"type": "String", "required": False, "description": "期货品种"},
        "start_week": {"type": "String", "required": False, "description": "开始周期"},
        "end_week": {"type": "String", "required": False, "description": "结束周期"},
        "exchange": {"type": "String", "required": False, "description": "交易所"},
        "offset": {"type": "Int64", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": ""},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "期货主要品种交易周报",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    exchange = Column("exchange", String(), nullable=False, comment="交易所代码")
    prd = Column("prd", String(), nullable=False, comment="期货品种代码")
    name = Column("name", String(), nullable=True, comment="品种名称")
    vol = Column("vol", Integer, nullable=True, comment="成交量(手)")
    vol_yoy = Column("vol_yoy", Float, nullable=True, comment="同比增减(%)")
    amount = Column("amount", Float, nullable=True, comment="成交金额(亿元)")
    amout_yoy = Column("amout_yoy", Float, nullable=True, comment="同比增减(%)")
    cumvol = Column("cumvol", Integer, nullable=True, comment="年累计成交总量(手)")
    cumvol_yoy = Column("cumvol_yoy", Float, nullable=True, comment="同比增减(%)")
    cumamt = Column("cumamt", Float, nullable=True, comment="年累计成交金额(亿元)")
    cumamt_yoy = Column("cumamt_yoy", Float, nullable=True, comment="同比增减(%)")
    open_interest = Column("open_interest", Integer, nullable=True, comment="持仓量(手)")
    interest_wow = Column("interest_wow", Float, nullable=True, comment="环比增减(%)")
    mc_close = Column("mc_close", Float, nullable=True, comment="本周主力合约收盘价")
    close_wow = Column("close_wow", Float, nullable=True, comment="环比涨跌(%)")
    week = Column("week", String(), nullable=False, comment="周期")
    week_date = Column("week_date", Date, nullable=True, comment="周日期")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FutWeeklyDetail.__table__, "engine", engines.ReplacingMergeTree(order_by=FutWeeklyDetail.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FutWeeklyDetail.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FutWeeklyDetail.__primary_key__),
            "order_by": ",".join(FutWeeklyDetail.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FutWeeklyDetail.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FutWeeklyDetail.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FutWeeklyDetail.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FutWeeklyDetail.__primary_key__,
        }
    )
except Exception:
    pass
