# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FutWsr(Base):
    """仓单日报"""

    __tablename__: str = "fut_wsr"
    __api_id__: ClassVar[int] = 140
    __api_name__: ClassVar[str] = "fut_wsr"
    __api_title__: ClassVar[str] = "仓单日报"
    __api_info_title__: ClassVar[str] = "仓单日报"
    __api_path__: ClassVar[List[str]] = ["数据接口", "期货数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 14]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["trade_date", "symbol", "warehouse", "wh_id"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "symbol": {"type": "String", "required": False, "description": "产品代码"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "exchange": {"type": "String", "required": False, "description": "交易所代码"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "仓单日报",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    symbol = Column("symbol", String(), nullable=False, comment="产品代码")
    fut_name = Column("fut_name", String(), nullable=True, comment="产品名称")
    warehouse = Column("warehouse", String(), nullable=False, comment="仓库名称")
    wh_id = Column("wh_id", String(), nullable=False, comment="仓库编号")
    pre_vol = Column("pre_vol", Integer, nullable=True, comment="昨日仓单量")
    vol = Column("vol", Integer, nullable=True, comment="今日仓单量")
    vol_chg = Column("vol_chg", Integer, nullable=True, comment="增减量")
    area = Column("area", String(), nullable=True, comment="地区")
    year = Column("year", String(), nullable=True, comment="年度")
    grade = Column("grade", String(), nullable=True, comment="等级")
    brand = Column("brand", String(), nullable=True, comment="品牌")
    place = Column("place", String(), nullable=True, comment="产地")
    pd = Column("pd", Integer, nullable=True, comment="升贴水")
    is_ct = Column("is_ct", String(), nullable=True, comment="是否折算仓单")
    unit = Column("unit", String(), nullable=True, comment="单位")
    exchange = Column("exchange", String(), nullable=True, comment="交易所")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FutWsr.__table__, "engine", engines.ReplacingMergeTree(order_by=FutWsr.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FutWsr.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FutWsr.__primary_key__),
            "order_by": ",".join(FutWsr.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FutWsr.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FutWsr.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FutWsr.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FutWsr.__primary_key__,
        }
    )
except Exception:
    pass
