# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class FxDaily(Base):
    """外汇日线行情"""

    __tablename__: str = "fx_daily"
    __api_id__: ClassVar[int] = 179
    __api_name__: ClassVar[str] = "fx_daily"
    __api_title__: ClassVar[str] = "外汇日线行情"
    __api_info_title__: ClassVar[str] = "外汇日线行情"
    __api_path__: ClassVar[List[str]] = ["数据接口", "外汇数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 18]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal", "fx_obasic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "TS代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期（GMT）"},
        "start_date": {"type": "String", "required": False, "description": "开始日期（GMT）"},
        "end_date": {"type": "String", "required": False, "description": "结束日期（GMT）"},
        "exchange": {"type": "String", "required": False, "description": "交易商"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "外汇日线行情",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="外汇代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    bid_open = Column("bid_open", Float, nullable=True, comment="买入开盘价")
    bid_close = Column("bid_close", Float, nullable=True, comment="买入收盘价")
    bid_high = Column("bid_high", Float, nullable=True, comment="买入最高价")
    bid_low = Column("bid_low", Float, nullable=True, comment="买入最低价")
    ask_open = Column("ask_open", Float, nullable=True, comment="卖出开盘价")
    ask_close = Column("ask_close", Float, nullable=True, comment="卖出收盘价")
    ask_high = Column("ask_high", Float, nullable=True, comment="卖出最高价")
    ask_low = Column("ask_low", Float, nullable=True, comment="卖出最低价")
    tick_qty = Column("tick_qty", Integer, nullable=True, comment="报价笔数")
    exchange = Column("exchange", String(), nullable=True, comment="交易商")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(FxDaily.__table__, "engine", engines.ReplacingMergeTree(order_by=FxDaily.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    FxDaily.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(FxDaily.__primary_key__),
            "order_by": ",".join(FxDaily.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    FxDaily.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": FxDaily.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    FxDaily.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": FxDaily.__primary_key__,
        }
    )
except Exception:
    pass
