# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class GgtMonthly(Base):
    """港股通每月成交统计"""

    __tablename__: str = "ggt_monthly"
    __api_id__: ClassVar[int] = 197
    __api_name__: ClassVar[str] = "ggt_monthly"
    __api_title__: ClassVar[str] = "港股通每月成交统计"
    __api_info_title__: ClassVar[str] = "港股通每月成交统计"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 4]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["month"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "month": {"type": "String", "required": False, "description": "月度"},
        "start_month": {"type": "String", "required": False, "description": "开始月度"},
        "end_month": {"type": "String", "required": False, "description": "结束月度"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "港股通每月成交统计",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    month = Column("month", String(), nullable=False, comment="交易日期")
    day_buy_amt = Column("day_buy_amt", Float, nullable=True, comment="当月日均买入成交金额(亿元)")
    day_buy_vol = Column("day_buy_vol", Float, nullable=True, comment="当月日均买入成交笔数(万笔)")
    day_sell_amt = Column("day_sell_amt", Float, nullable=True, comment="当月日均卖出成交金额(亿元)")
    day_sell_vol = Column("day_sell_vol", Float, nullable=True, comment="当月日均卖出成交笔数(万笔)")
    total_buy_amt = Column("total_buy_amt", Float, nullable=True, comment="总买入成交金额(亿元)")
    total_buy_vol = Column("total_buy_vol", Float, nullable=True, comment="总买入成交笔数(万笔)")
    total_sell_amt = Column("total_sell_amt", Float, nullable=True, comment="总卖出成交金额(亿元)")
    total_sell_vol = Column("total_sell_vol", Float, nullable=True, comment="总卖出成交笔数(万笔)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(GgtMonthly.__table__, "engine", engines.ReplacingMergeTree(order_by=GgtMonthly.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    GgtMonthly.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(GgtMonthly.__primary_key__),
            "order_by": ",".join(GgtMonthly.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    GgtMonthly.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": GgtMonthly.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    GgtMonthly.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": GgtMonthly.__primary_key__,
        }
    )
except Exception:
    pass
