# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class HkBasic(Base):
    """港股基础信息"""

    __tablename__: str = "hk_basic"
    __api_id__: ClassVar[int] = 191
    __api_name__: ClassVar[str] = "hk_basic"
    __api_title__: ClassVar[str] = "港股基础信息"
    __api_info_title__: ClassVar[str] = "港股基础信息"
    __api_path__: ClassVar[List[str]] = ["数据接口", "港股数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 19]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "TS代码"},
        "list_status": {"type": "String", "required": False, "description": "上市状态 L上市 D退市 P暂停上市"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "港股基础信息",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="")
    name = Column("name", String(), nullable=True, comment="股票简称")
    fullname = Column("fullname", String(), nullable=True, comment="公司全称")
    enname = Column("enname", String(), nullable=True, comment="英文名称")
    cn_spell = Column("cn_spell", String(), nullable=True, comment="拼音")
    market = Column("market", String(), nullable=True, comment="市场类别")
    list_status = Column("list_status", String(), nullable=True, comment="上市状态")
    list_date = Column("list_date", Date, nullable=True, comment="上市日期")
    delist_date = Column("delist_date", Date, nullable=True, comment="退市日期")
    trade_unit = Column("trade_unit", Float, nullable=True, comment="交易单位")
    isin = Column("isin", String(), nullable=True, comment="ISIN代码")
    curr_type = Column("curr_type", String(), nullable=True, comment="货币代码")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(HkBasic.__table__, "engine", engines.ReplacingMergeTree(order_by=HkBasic.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    HkBasic.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(HkBasic.__primary_key__),
            "order_by": ",".join(HkBasic.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    HkBasic.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": HkBasic.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    HkBasic.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": HkBasic.__primary_key__,
        }
    )
except Exception:
    pass
