# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class HkCashflow(Base):
    """港股现金流量表"""

    __tablename__: str = "hk_cashflow"
    __api_id__: ClassVar[int] = 391
    __api_name__: ClassVar[str] = "hk_cashflow"
    __api_title__: ClassVar[str] = "港股现金流量表"
    __api_info_title__: ClassVar[str] = "港股现金流量表"
    __api_path__: ClassVar[List[str]] = ["数据接口", "港股数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 19]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["hk_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "end_date", "ind_name"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": True, "description": "股票代码"},
        "period": {
            "type": "String",
            "required": False,
            "description": "报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)",
        },
        "ind_name": {"type": "String", "required": False, "description": "指标名(如：新增借款）"},
        "start_date": {"type": "String", "required": False, "description": "报告期开始时间（格式：YYYYMMDD）"},
        "end_date": {"type": "String", "required": False, "description": "报告结束始时间（格式：YYYYMMDD）"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "港股现金流量表",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    end_date = Column("end_date", Date, nullable=False, comment="报告期")
    name = Column("name", String(), nullable=True, comment="股票名称")
    ind_name = Column("ind_name", String(), nullable=False, comment="财务科目名称")
    ind_value = Column("ind_value", Float, nullable=True, comment="财务科目值")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(HkCashflow.__table__, "engine", engines.ReplacingMergeTree(order_by=HkCashflow.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    HkCashflow.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(HkCashflow.__primary_key__),
            "order_by": ",".join(HkCashflow.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    HkCashflow.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": HkCashflow.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    HkCashflow.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": HkCashflow.__primary_key__,
        }
    )
except Exception:
    pass
