# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class HkDailyAdj(Base):
    """港股复权行情"""

    __tablename__: str = "hk_daily_adj"
    __api_id__: ClassVar[int] = 339
    __api_name__: ClassVar[str] = "hk_daily_adj"
    __api_title__: ClassVar[str] = "港股复权行情"
    __api_info_title__: ClassVar[str] = "港股复权行情"
    __api_path__: ClassVar[List[str]] = ["数据接口", "港股数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 19]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["hk_tradecal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码（e.g. 00001.HK）"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期（YYYYMMDD）"},
        "start_date": {"type": "String", "required": False, "description": "开始日期（YYYYMMDD）"},
        "end_date": {"type": "String", "required": False, "description": "结束日期（YYYYMMDD）"},
        "offset": {"type": "Int64", "required": False, "description": "开始行数"},
        "limit": {"type": "Int64", "required": False, "description": "每页行数行数"},
        "symbol": {"type": "String", "required": False, "description": ""},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "港股复权行情",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    close = Column("close", Float, nullable=True, comment="收盘价")
    open = Column("open", Float, nullable=True, comment="开盘价")
    high = Column("high", Float, nullable=True, comment="最高价")
    low = Column("low", Float, nullable=True, comment="最低价")
    pre_close = Column("pre_close", Float, nullable=True, comment="昨收价")
    change = Column("change", Float, nullable=True, comment="涨跌额")
    pct_change = Column("pct_change", Float, nullable=True, comment="涨跌幅")
    vol = Column("vol", String(), nullable=True, comment="成交量")
    amount = Column("amount", Float, nullable=True, comment="成交额")
    vwap = Column("vwap", Float, nullable=True, comment="平均价")
    adj_factor = Column("adj_factor", Float, nullable=True, comment="复权因子")
    turnover_ratio = Column("turnover_ratio", Float, nullable=True, comment="换手率")
    free_share = Column("free_share", String(), nullable=True, comment="流通股本")
    total_share = Column("total_share", String(), nullable=True, comment="总股本")
    free_mv = Column("free_mv", Float, nullable=True, comment="流通市值")
    total_mv = Column("total_mv", Float, nullable=True, comment="总市值")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(HkDailyAdj.__table__, "engine", engines.ReplacingMergeTree(order_by=HkDailyAdj.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    HkDailyAdj.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(HkDailyAdj.__primary_key__),
            "order_by": ",".join(HkDailyAdj.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    HkDailyAdj.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": HkDailyAdj.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    HkDailyAdj.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": HkDailyAdj.__primary_key__,
        }
    )
except Exception:
    pass
