# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class HkHold(Base):
    """沪深股通持股明细"""

    __tablename__: str = "hk_hold"
    __api_id__: ClassVar[int] = 188
    __api_name__: ClassVar[str] = "hk_hold"
    __api_title__: ClassVar[str] = "沪深股通持股明细"
    __api_info_title__: ClassVar[str] = "沪深股通持股明细"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "特色数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 7]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["hk_tradecal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "code": {"type": "String", "required": False, "description": "交易所代码"},
        "ts_code": {"type": "String", "required": False, "description": "TS股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "exchange": {"type": "String", "required": False, "description": "SH沪股通SZ深股通"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "沪深股通持股明细",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    code = Column("code", String(), nullable=True, comment="原始代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    ts_code = Column("ts_code", String(16), nullable=False, comment="TS代码")
    name = Column("name", String(), nullable=True, comment="股票名称")
    vol = Column("vol", String(), nullable=True, comment="持股数量")
    ratio = Column("ratio", Float, nullable=True, comment="持股占比")
    exchange = Column("exchange", String(), nullable=True, comment="类型：SH沪股通SZ深港通")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(HkHold.__table__, "engine", engines.ReplacingMergeTree(order_by=HkHold.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    HkHold.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(HkHold.__primary_key__),
            "order_by": ",".join(HkHold.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    HkHold.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": HkHold.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    HkHold.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": HkHold.__primary_key__,
        }
    )
except Exception:
    pass
