# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class IndexWeight(Base):
    """指数成分和权重"""

    __tablename__: str = "index_weight"
    __api_id__: ClassVar[int] = 96
    __api_name__: ClassVar[str] = "index_weight"
    __api_title__: ClassVar[str] = "指数成分和权重"
    __api_info_title__: ClassVar[str] = "指数成分和权重"
    __api_path__: ClassVar[List[str]] = ["数据接口", "指数专题"]
    __api_path_ids__: ClassVar[List[int]] = [1, 12]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["index_basic"]
    __primary_key__: ClassVar[List[str]] = ["index_code", "con_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "index_code": {"type": "String", "required": False, "description": "指数代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "ts_code": {"type": "String", "required": False, "description": "股票成分代码"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "指数成分和权重",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    index_code = Column("index_code", String(), nullable=False, comment="指数代码")
    con_code = Column("con_code", String(), nullable=False, comment="成分代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    weight = Column("weight", Float, nullable=True, comment="权重")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(IndexWeight.__table__, "engine", engines.ReplacingMergeTree(order_by=IndexWeight.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    IndexWeight.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(IndexWeight.__primary_key__),
            "order_by": ",".join(IndexWeight.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    IndexWeight.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": IndexWeight.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    IndexWeight.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": IndexWeight.__primary_key__,
        }
    )
except Exception:
    pass
