# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class IrmQaSh(Base):
    """上证e互动问答"""

    __tablename__: str = "irm_qa_sh"
    __api_id__: ClassVar[int] = 366
    __api_name__: ClassVar[str] = "irm_qa_sh"
    __api_title__: ClassVar[str] = "上证e互动问答"
    __api_info_title__: ClassVar[str] = "上证e互动问答"
    __api_path__: ClassVar[List[str]] = ["数据接口", "大模型语料专题数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 36]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期（格式：YYYYMMDD，下同）"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "pub_start": {"type": "String", "required": False, "description": "发布开始时间(格式：2025-06-03 16:43:03)"},
        "pub_end": {"type": "String", "required": False, "description": "发布结束时间"},
        "offset": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "String", "required": False, "description": ""},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "上证e互动问答",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    name = Column("name", String(), nullable=True, comment="公司名称")
    trade_date = Column("trade_date", Date, nullable=False, comment="日期")
    q = Column("q", String(), nullable=True, comment="问题")
    a = Column("a", String(), nullable=True, comment="回复")
    pub_time = Column("pub_time", DateTime, nullable=True, comment="回复时间")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(IrmQaSh.__table__, "engine", engines.ReplacingMergeTree(order_by=IrmQaSh.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    IrmQaSh.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(IrmQaSh.__primary_key__),
            "order_by": ",".join(IrmQaSh.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    IrmQaSh.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": IrmQaSh.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    IrmQaSh.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": IrmQaSh.__primary_key__,
        }
    )
except Exception:
    pass
