# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class Jinse(Base):
    """金色财经"""

    __tablename__: str = "jinse"
    __api_id__: ClassVar[int] = 70
    __api_name__: ClassVar[str] = "jinse"
    __api_title__: ClassVar[str] = "金色财经"
    __api_info_title__: ClassVar[str] = "金色财经"
    __api_path__: ClassVar[List[str]] = ["另类数据", "资讯公告"]
    __api_path_ids__: ClassVar[List[int]] = [37, 40]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["datetime", "title"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "start_date": {"type": "String", "required": False, "description": "开始时间"},
        "end_date": {"type": "String", "required": False, "description": "结束时间"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "金色财经",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    title = Column("title", String(), nullable=False, comment="标题")
    content = Column("content", String(), nullable=True, comment="内容")
    type = Column("type", String(), nullable=True, comment="类型")
    url = Column("url", String(), nullable=True, comment="URL")
    datetime = Column("datetime", Date, nullable=False, comment="时间")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(Jinse.__table__, "engine", engines.ReplacingMergeTree(order_by=Jinse.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    Jinse.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(Jinse.__primary_key__),
            "order_by": ",".join(Jinse.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    Jinse.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": Jinse.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    Jinse.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": Jinse.__primary_key__,
        }
    )
except Exception:
    pass
