# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class KplList(Base):
    """榜单数据(开盘啦)"""

    __tablename__: str = "kpl_list"
    __api_id__: ClassVar[int] = 347
    __api_name__: ClassVar[str] = "kpl_list"
    __api_title__: ClassVar[str] = "榜单数据(开盘啦)"
    __api_info_title__: ClassVar[str] = "榜单数据(开盘啦)"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "打板专题数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 10]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "tag": {"type": "String", "required": False, "description": "板单类型（涨停|炸板|跌停，默认涨停)"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "榜单数据(开盘啦)",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="代码")
    name = Column("name", String(), nullable=True, comment="名称")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易时间")
    lu_time = Column("lu_time", String(), nullable=True, comment="涨停时间")
    ld_time = Column("ld_time", String(), nullable=True, comment="跌停时间")
    open_time = Column("open_time", String(), nullable=True, comment="开板时间")
    last_time = Column("last_time", String(), nullable=True, comment="最后涨停时间")
    lu_desc = Column("lu_desc", String(), nullable=True, comment="涨停原因")
    tag = Column("tag", String(), nullable=True, comment="标签|类别")
    theme = Column("theme", String(), nullable=True, comment="板块")
    net_change = Column("net_change", Float, nullable=True, comment="主力净额(元)")
    bid_amount = Column("bid_amount", Float, nullable=True, comment="竞价成交额(元)")
    status = Column("status", String(), nullable=True, comment="状态")
    bid_change = Column("bid_change", Float, nullable=True, comment="竞价成交额(元|个)")
    bid_turnover = Column("bid_turnover", Float, nullable=True, comment="竞价换手)%")
    lu_bid_vol = Column("lu_bid_vol", Float, nullable=True, comment="涨停委买额(元|个)")
    pct_chg = Column("pct_chg", Float, nullable=True, comment="涨跌幅%")
    bid_pct_chg = Column("bid_pct_chg", Float, nullable=True, comment="竞价涨幅%")
    rt_pct_chg = Column("rt_pct_chg", Float, nullable=True, comment="实时涨幅%")
    limit_order = Column("limit_order", Float, nullable=True, comment="封单(元|个)")
    amount = Column("amount", Float, nullable=True, comment="成交额(元|个)")
    turnover_rate = Column("turnover_rate", Float, nullable=True, comment="换手率%")
    free_float = Column("free_float", Float, nullable=True, comment="实际流通(元|个)")
    lu_limit_order = Column("lu_limit_order", Float, nullable=True, comment="最大封单(元|个)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(KplList.__table__, "engine", engines.ReplacingMergeTree(order_by=KplList.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    KplList.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(KplList.__primary_key__),
            "order_by": ",".join(KplList.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    KplList.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": KplList.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    KplList.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": KplList.__primary_key__,
        }
    )
except Exception:
    pass
