# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class LimitListD(Base):
    """涨跌停和炸板数据"""

    __tablename__: str = "limit_list_d"
    __api_id__: ClassVar[int] = 298
    __api_name__: ClassVar[str] = "limit_list_d"
    __api_title__: ClassVar[str] = "涨跌停和炸板数据"
    __api_info_title__: ClassVar[str] = "涨跌停和炸板数据"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "打板专题数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 10]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "limit_type": {"type": "String", "required": False, "description": "涨跌停类型U涨停D跌停Z炸板"},
        "exchange": {"type": "String", "required": False, "description": "交易所（SH上交所SZ深交所BJ北交所）"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "涨跌停和炸板数据",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    industry = Column("industry", String(), nullable=True, comment="所属行业")
    name = Column("name", String(), nullable=True, comment="股票名称")
    close = Column("close", Float, nullable=True, comment="收盘价")
    pct_chg = Column("pct_chg", Float, nullable=True, comment="涨跌幅")
    swing = Column("swing", Float, nullable=True, comment="振幅")
    amount = Column("amount", Float, nullable=True, comment="成交额")
    limit_amount = Column("limit_amount", Float, nullable=True, comment="板上成交金额")
    float_mv = Column("float_mv", Float, nullable=True, comment="流通市值")
    total_mv = Column("total_mv", Float, nullable=True, comment="总市值")
    turnover_ratio = Column("turnover_ratio", Float, nullable=True, comment="换手率")
    fd_amount = Column("fd_amount", Float, nullable=True, comment="封单金额")
    first_time = Column("first_time", String(), nullable=True, comment="首次封板时间")
    last_time = Column("last_time", String(), nullable=True, comment="最后封板时间")
    open_times = Column("open_times", Integer, nullable=True, comment="炸板次数")
    up_stat = Column("up_stat", String(), nullable=True, comment="涨停统计")
    limit_times = Column("limit_times", Integer, nullable=True, comment="连板数")
    limit = Column("limit", String(), nullable=True, comment="D跌停U涨停Z炸板")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(LimitListD.__table__, "engine", engines.ReplacingMergeTree(order_by=LimitListD.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    LimitListD.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(LimitListD.__primary_key__),
            "order_by": ",".join(LimitListD.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    LimitListD.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": LimitListD.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    LimitListD.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": LimitListD.__primary_key__,
        }
    )
except Exception:
    pass
