# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class MoneyflowMktDc(Base):
    """大盘资金流向(DC)"""

    __tablename__: str = "moneyflow_mkt_dc"
    __api_id__: ClassVar[int] = 345
    __api_name__: ClassVar[str] = "moneyflow_mkt_dc"
    __api_title__: ClassVar[str] = "大盘资金流向(DC)"
    __api_info_title__: ClassVar[str] = "大盘资金流向(DC)"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "资金流向数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 9]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "交易日期(格式：YYYYMMDD，下同)"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "大盘资金流向(DC)",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    close_sh = Column("close_sh", Float, nullable=True, comment="上证收盘价(元)")
    pct_change_sh = Column("pct_change_sh", Float, nullable=True, comment="上证涨跌幅(%)")
    close_sz = Column("close_sz", Float, nullable=True, comment="深证收盘价(元)")
    pct_change_sz = Column("pct_change_sz", Float, nullable=True, comment="深证涨跌幅(%)")
    net_amount = Column("net_amount", Float, nullable=True, comment="今日主力净流入 净额(元)")
    net_amount_rate = Column("net_amount_rate", Float, nullable=True, comment="今日主力净流入净占比%")
    buy_elg_amount = Column("buy_elg_amount", Float, nullable=True, comment="今日超大单净流入 净额(元)")
    buy_elg_amount_rate = Column("buy_elg_amount_rate", Float, nullable=True, comment="今日超大单净流入 净占比%")
    buy_lg_amount = Column("buy_lg_amount", Float, nullable=True, comment="今日大单净流入 净额(元)")
    buy_lg_amount_rate = Column("buy_lg_amount_rate", Float, nullable=True, comment="今日大单净流入 净占比%")
    buy_md_amount = Column("buy_md_amount", Float, nullable=True, comment="今日中单净流入 净额(元)")
    buy_md_amount_rate = Column("buy_md_amount_rate", Float, nullable=True, comment="今日中单净流入 净占比%")
    buy_sm_amount = Column("buy_sm_amount", Float, nullable=True, comment="今日小单净流入 净额(元)")
    buy_sm_amount_rate = Column("buy_sm_amount_rate", Float, nullable=True, comment="今日小单净流入 净占比%")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(MoneyflowMktDc.__table__, "engine", engines.ReplacingMergeTree(order_by=MoneyflowMktDc.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    MoneyflowMktDc.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(MoneyflowMktDc.__primary_key__),
            "order_by": ",".join(MoneyflowMktDc.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    MoneyflowMktDc.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": MoneyflowMktDc.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    MoneyflowMktDc.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": MoneyflowMktDc.__primary_key__,
        }
    )
except Exception:
    pass
