# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class MoneyflowHsgt(Base):
    """沪深港通资金流向"""

    __tablename__: str = "moneyflow_hsgt"
    __api_id__: ClassVar[int] = 47
    __api_name__: ClassVar[str] = "moneyflow_hsgt"
    __api_title__: ClassVar[str] = "沪深港通资金流向"
    __api_info_title__: ClassVar[str] = "沪深港通资金流向"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "资金流向数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 9]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "沪深港通资金流向",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    ggt_ss = Column("ggt_ss", String(), nullable=True, comment="港股通(上海)")
    ggt_sz = Column("ggt_sz", String(), nullable=True, comment="港股通(深圳)")
    hgt = Column("hgt", String(), nullable=True, comment="沪股通")
    sgt = Column("sgt", String(), nullable=True, comment="深股通")
    north_money = Column("north_money", String(), nullable=True, comment="北向资金")
    south_money = Column("south_money", String(), nullable=True, comment="南向资金")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(MoneyflowHsgt.__table__, "engine", engines.ReplacingMergeTree(order_by=MoneyflowHsgt.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    MoneyflowHsgt.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(MoneyflowHsgt.__primary_key__),
            "order_by": ",".join(MoneyflowHsgt.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    MoneyflowHsgt.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": MoneyflowHsgt.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    MoneyflowHsgt.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": MoneyflowHsgt.__primary_key__,
        }
    )
except Exception:
    pass
