# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class MoneyflowIndThs(Base):
    """行业资金流向(THS)"""

    __tablename__: str = "moneyflow_ind_ths"
    __api_id__: ClassVar[int] = 343
    __api_name__: ClassVar[str] = "moneyflow_ind_ths"
    __api_title__: ClassVar[str] = "行业资金流向(THS)"
    __api_info_title__: ClassVar[str] = "行业资金流向(THS)"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "资金流向数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 9]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal", "ths_index"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期(格式：YYYYMMDD，下同)"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "行业资金流向(THS)",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    ts_code = Column("ts_code", String(16), nullable=False, comment="板块代码")
    industry = Column("industry", String(), nullable=True, comment="板块名称")
    lead_stock = Column("lead_stock", String(), nullable=True, comment="领涨股票名称")
    close = Column("close", Float, nullable=True, comment="收盘指数")
    pct_change = Column("pct_change", Float, nullable=True, comment="指数涨跌幅")
    company_num = Column("company_num", Integer, nullable=True, comment="公司数量")
    pct_change_stock = Column("pct_change_stock", Float, nullable=True, comment="领涨股涨跌幅")
    close_price = Column("close_price", Float, nullable=True, comment="领涨股最新价")
    net_buy_amount = Column("net_buy_amount", Float, nullable=True, comment="流入资金(元)")
    net_sell_amount = Column("net_sell_amount", Float, nullable=True, comment="流出资金(元)")
    net_amount = Column("net_amount", Float, nullable=True, comment="净额(元)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(MoneyflowIndThs.__table__, "engine", engines.ReplacingMergeTree(order_by=MoneyflowIndThs.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    MoneyflowIndThs.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(MoneyflowIndThs.__primary_key__),
            "order_by": ",".join(MoneyflowIndThs.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    MoneyflowIndThs.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": MoneyflowIndThs.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    MoneyflowIndThs.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": MoneyflowIndThs.__primary_key__,
        }
    )
except Exception:
    pass
