# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class Moneyflow(Base):
    """个股资金流向"""

    __tablename__: str = "moneyflow"
    __api_id__: ClassVar[int] = 170
    __api_name__: ClassVar[str] = "moneyflow"
    __api_title__: ClassVar[str] = "个股资金流向"
    __api_info_title__: ClassVar[str] = "个股资金流向"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "资金流向数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 9]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期（格式：YYYYMMDD，下同）"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "个股资金流向",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="TS代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    buy_sm_vol = Column("buy_sm_vol", Integer, nullable=True, comment="小单买入量(手)")
    buy_sm_amount = Column("buy_sm_amount", Float, nullable=True, comment="小单买入金额(万元)")
    sell_sm_vol = Column("sell_sm_vol", Integer, nullable=True, comment="小单卖出量(手)")
    sell_sm_amount = Column("sell_sm_amount", Float, nullable=True, comment="小单卖出金额(万元)")
    buy_md_vol = Column("buy_md_vol", Integer, nullable=True, comment="中单买入量(手)")
    buy_md_amount = Column("buy_md_amount", Float, nullable=True, comment="中单买入金额(万元)")
    sell_md_vol = Column("sell_md_vol", Integer, nullable=True, comment="中单卖出量(手)")
    sell_md_amount = Column("sell_md_amount", Float, nullable=True, comment="中单卖出金额(万元)")
    buy_lg_vol = Column("buy_lg_vol", Integer, nullable=True, comment="大单买入量(手)")
    buy_lg_amount = Column("buy_lg_amount", Float, nullable=True, comment="大单买入金额(万元)")
    sell_lg_vol = Column("sell_lg_vol", Integer, nullable=True, comment="大单卖出量(手)")
    sell_lg_amount = Column("sell_lg_amount", Float, nullable=True, comment="大单卖出金额(万元)")
    buy_elg_vol = Column("buy_elg_vol", Integer, nullable=True, comment="特大单买入量(手)")
    buy_elg_amount = Column("buy_elg_amount", Float, nullable=True, comment="特大单买入金额(万元)")
    sell_elg_vol = Column("sell_elg_vol", Integer, nullable=True, comment="特大单卖出量(手)")
    sell_elg_amount = Column("sell_elg_amount", Float, nullable=True, comment="特大单卖出金额(万元)")
    net_mf_vol = Column("net_mf_vol", Integer, nullable=True, comment="净流入量(手)")
    net_mf_amount = Column("net_mf_amount", Float, nullable=True, comment="净流入额(万元)")
    trade_count = Column("trade_count", Integer, nullable=True, comment="交易笔数")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(Moneyflow.__table__, "engine", engines.ReplacingMergeTree(order_by=Moneyflow.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    Moneyflow.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(Moneyflow.__primary_key__),
            "order_by": ",".join(Moneyflow.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    Moneyflow.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": Moneyflow.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    Moneyflow.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": Moneyflow.__primary_key__,
        }
    )
except Exception:
    pass
