# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class NewShare(Base):
    """IPO新股上市"""

    __tablename__: str = "new_share"
    __api_id__: ClassVar[int] = 123
    __api_name__: ClassVar[str] = "new_share"
    __api_title__: ClassVar[str] = "IPO新股上市"
    __api_info_title__: ClassVar[str] = "IPO新股上市"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "基础数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 3]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "IPO新股上市",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="TS股票代码")
    sub_code = Column("sub_code", String(), nullable=True, comment="申购代码")
    name = Column("name", String(), nullable=True, comment="名称")
    ipo_date = Column("ipo_date", Date, nullable=True, comment="上网发行日期")
    issue_date = Column("issue_date", Date, nullable=True, comment="上市日期")
    amount = Column("amount", Float, nullable=True, comment="发行总量(万股)")
    market_amount = Column("market_amount", Float, nullable=True, comment="上网发行总量(万股)")
    price = Column("price", Float, nullable=True, comment="发行价格")
    pe = Column("pe", Float, nullable=True, comment="市盈率")
    limit_amount = Column("limit_amount", Float, nullable=True, comment="个人申购上限(万股)")
    funds = Column("funds", Float, nullable=True, comment="募集资金(亿元)")
    ballot = Column("ballot", Float, nullable=True, comment="中签率")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(NewShare.__table__, "engine", engines.ReplacingMergeTree(order_by=NewShare.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    NewShare.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(NewShare.__primary_key__),
            "order_by": ",".join(NewShare.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    NewShare.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": NewShare.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    NewShare.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": NewShare.__primary_key__,
        }
    )
except Exception:
    pass
