# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class PledgeStat(Base):
    """股权质押统计数据"""

    __tablename__: str = "pledge_stat"
    __api_id__: ClassVar[int] = 110
    __api_name__: ClassVar[str] = "pledge_stat"
    __api_title__: ClassVar[str] = "股权质押统计数据"
    __api_info_title__: ClassVar[str] = "股权质押统计数据"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "参考数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 6]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code", "end_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "end_date": {"type": "String", "required": False, "description": "截止日期（格式：YYYYMMDD）"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "股权质押统计数据",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="TS代码")
    end_date = Column("end_date", Date, nullable=False, comment="截至日期")
    pledge_count = Column("pledge_count", Integer, nullable=True, comment="质押次数")
    unrest_pledge = Column("unrest_pledge", Float, nullable=True, comment="无限售股质押数量(万)")
    rest_pledge = Column("rest_pledge", Float, nullable=True, comment="限售股份质押数量(万)")
    total_share = Column("total_share", Float, nullable=True, comment="总股本")
    pledge_ratio = Column("pledge_ratio", Float, nullable=True, comment="质押比例")
    update_flag = Column("update_flag", Date, nullable=True, comment="更新标识")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(PledgeStat.__table__, "engine", engines.ReplacingMergeTree(order_by=PledgeStat.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    PledgeStat.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(PledgeStat.__primary_key__),
            "order_by": ",".join(PledgeStat.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    PledgeStat.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": PledgeStat.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    PledgeStat.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": PledgeStat.__primary_key__,
        }
    )
except Exception:
    pass
