# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class RtMin(Base):
    """实时分钟"""

    __tablename__: str = "rt_min"
    __api_id__: ClassVar[int] = 374
    __api_name__: ClassVar[str] = "rt_min"
    __api_title__: ClassVar[str] = "实时分钟"
    __api_info_title__: ClassVar[str] = "实时分钟"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 4]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code", "freq", "time"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "topic": {"type": "String", "required": False, "description": ""},
        "freq": {"type": "String", "required": True, "description": "1MIN,5MIN,15MIN,30MIN,60MIN"},
        "ts_code": {"type": "String", "required": True, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "实时分钟",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="基金代码")
    freq = Column("freq", String(), nullable=False, comment="频度")
    time = Column("time", String(), nullable=False, comment="交易时间")
    open = Column("open", Float, nullable=True, comment="开票")
    close = Column("close", Float, nullable=True, comment="收盘")
    high = Column("high", Float, nullable=True, comment="最高")
    low = Column("low", Float, nullable=True, comment="最低")
    vol = Column("vol", Float, nullable=True, comment="成交量")
    amount = Column("amount", Float, nullable=True, comment="成交额")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(RtMin.__table__, "engine", engines.ReplacingMergeTree(order_by=RtMin.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    RtMin.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(RtMin.__primary_key__),
            "order_by": ",".join(RtMin.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    RtMin.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": RtMin.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    RtMin.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": RtMin.__primary_key__,
        }
    )
except Exception:
    pass
