# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class SfMonth(Base):
    """社融增量(月度)"""

    __tablename__: str = "sf_month"
    __api_id__: ClassVar[int] = 310
    __api_name__: ClassVar[str] = "sf_month"
    __api_title__: ClassVar[str] = "社融增量(月度)"
    __api_info_title__: ClassVar[str] = "社融增量(月度)"
    __api_path__: ClassVar[List[str]] = ["数据接口", "宏观经济", "国内宏观", "金融", "社会融资"]
    __api_path_ids__: ClassVar[List[int]] = [1, 23, 24, 28, 30]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["month"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "m": {
            "type": "String",
            "required": False,
            "description": "月份（YYYYMM，下同），支持多个月份同时输入，逗号分隔",
        },
        "start_m": {"type": "String", "required": False, "description": "开始月份"},
        "end_m": {"type": "String", "required": False, "description": "结束月份"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "社融增量(月度)",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    month = Column("month", String(), nullable=False, comment="月度")
    inc_month = Column("inc_month", Float, nullable=True, comment="社融增量当月值(亿元)")
    inc_cumval = Column("inc_cumval", Float, nullable=True, comment="社融增量累计值(亿元)")
    stk_endval = Column("stk_endval", Float, nullable=True, comment="社融存量期末值(万亿元)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(SfMonth.__table__, "engine", engines.ReplacingMergeTree(order_by=SfMonth.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    SfMonth.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(SfMonth.__primary_key__),
            "order_by": ",".join(SfMonth.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    SfMonth.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": SfMonth.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    SfMonth.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": SfMonth.__primary_key__,
        }
    )
except Exception:
    pass
