# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class StkSurv(Base):
    """机构调研数据"""

    __tablename__: str = "stk_surv"
    __api_id__: ClassVar[int] = 275
    __api_name__: ClassVar[str] = "stk_surv"
    __api_title__: ClassVar[str] = "机构调研数据"
    __api_info_title__: ClassVar[str] = "机构调研数据"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "特色数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 7]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["stock_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "surv_date", "rece_org"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "调研日期"},
        "start_date": {"type": "String", "required": False, "description": "调研开始日期"},
        "end_date": {"type": "String", "required": False, "description": "调研结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "机构调研数据",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    name = Column("name", String(), nullable=True, comment="股票名称")
    surv_date = Column("surv_date", Date, nullable=False, comment="调研日期")
    fund_visitors = Column("fund_visitors", String(), nullable=True, comment="机构参与人员")
    rece_place = Column("rece_place", String(), nullable=True, comment="接待地点")
    rece_mode = Column("rece_mode", String(), nullable=True, comment="接待方式")
    rece_org = Column("rece_org", String(), nullable=False, comment="接待的公司")
    org_type = Column("org_type", String(), nullable=True, comment="接待公司类型")
    comp_rece = Column("comp_rece", String(), nullable=True, comment="上市公司接待人员")
    content = Column("content", String(), nullable=True, comment="调研内容")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(StkSurv.__table__, "engine", engines.ReplacingMergeTree(order_by=StkSurv.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    StkSurv.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(StkSurv.__primary_key__),
            "order_by": ",".join(StkSurv.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    StkSurv.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": StkSurv.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    StkSurv.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": StkSurv.__primary_key__,
        }
    )
except Exception:
    pass
