# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class StkNineturn(Base):
    """神奇九转指标"""

    __tablename__: str = "stk_nineturn"
    __api_id__: ClassVar[int] = 364
    __api_name__: ClassVar[str] = "stk_nineturn"
    __api_title__: ClassVar[str] = "神奇九转指标"
    __api_info_title__: ClassVar[str] = "神奇九转指标"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "特色数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 7]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "freq": {"type": "String", "required": False, "description": "频率(日daily,分钟60min)"},
        "start_date": {"type": "String", "required": False, "description": "开始时间"},
        "end_date": {"type": "String", "required": False, "description": "结束时间"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "神奇九转指标",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    freq = Column("freq", String(), nullable=True, comment="频率(日daily,分钟60min)")
    open = Column("open", Float, nullable=True, comment="开盘价")
    high = Column("high", Float, nullable=True, comment="最高价")
    low = Column("low", Float, nullable=True, comment="最低价")
    close = Column("close", Float, nullable=True, comment="收盘价")
    vol = Column("vol", Float, nullable=True, comment="成交量")
    amount = Column("amount", Float, nullable=True, comment="成交额")
    up_count = Column("up_count", Float, nullable=True, comment="上九转计数")
    down_count = Column("down_count", Float, nullable=True, comment="下九转计数")
    nine_up_turn = Column("nine_up_turn", String(), nullable=True, comment="是否上九转)+9表示上九转")
    nine_down_turn = Column("nine_down_turn", String(), nullable=True, comment="是否下九转-9表示下九转")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(StkNineturn.__table__, "engine", engines.ReplacingMergeTree(order_by=StkNineturn.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    StkNineturn.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(StkNineturn.__primary_key__),
            "order_by": ",".join(StkNineturn.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    StkNineturn.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": StkNineturn.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    StkNineturn.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": StkNineturn.__primary_key__,
        }
    )
except Exception:
    pass
