# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class StkAhComparison(Base):
    """AH股比价"""

    __tablename__: str = "stk_ah_comparison"
    __api_id__: ClassVar[int] = 399
    __api_name__: ClassVar[str] = "stk_ah_comparison"
    __api_title__: ClassVar[str] = "AH股比价"
    __api_info_title__: ClassVar[str] = "AH股比价"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "特色数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 7]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "hk_code": {"type": "String", "required": False, "description": "港股股票代码"},
        "ts_code": {"type": "String", "required": False, "description": "A股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "AH股比价",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    hk_code = Column("hk_code", String(), nullable=True, comment="港股股票代码")
    ts_code = Column("ts_code", String(16), nullable=False, comment="A股股票代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    hk_name = Column("hk_name", String(), nullable=True, comment="港股股票名称")
    hk_pct_chg = Column("hk_pct_chg", Float, nullable=True, comment="港股股票涨跌幅")
    hk_close = Column("hk_close", Float, nullable=True, comment="港股股票收盘价")
    name = Column("name", String(), nullable=True, comment="A股股票名称")
    close = Column("close", Float, nullable=True, comment="A股股票收盘价")
    pct_chg = Column("pct_chg", Float, nullable=True, comment="A股股票涨跌幅")
    ah_comparison = Column("ah_comparison", Float, nullable=True, comment="比价(A/H)")
    ah_premium = Column("ah_premium", Float, nullable=True, comment="溢价(A/H)%")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(StkAhComparison.__table__, "engine", engines.ReplacingMergeTree(order_by=StkAhComparison.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    StkAhComparison.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(StkAhComparison.__primary_key__),
            "order_by": ",".join(StkAhComparison.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    StkAhComparison.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": StkAhComparison.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    StkAhComparison.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": StkAhComparison.__primary_key__,
        }
    )
except Exception:
    pass
