# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class StkHoldernumber(Base):
    """股东人数"""

    __tablename__: str = "stk_holdernumber"
    __api_id__: ClassVar[int] = 166
    __api_name__: ClassVar[str] = "stk_holdernumber"
    __api_title__: ClassVar[str] = "股东人数"
    __api_info_title__: ClassVar[str] = "股东人数"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "参考数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 6]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["stock_basic"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "end_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "TS股票代码"},
        "ann_date": {"type": "String", "required": False, "description": "公告日期"},
        "enddate": {"type": "String", "required": False, "description": "截止日期"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "股东人数",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="TS股票代码")
    ann_date = Column("ann_date", Date, nullable=True, comment="公告日期")
    end_date = Column("end_date", Date, nullable=False, comment="截止日期")
    holder_nums = Column("holder_nums", Integer, nullable=True, comment="股东户数")
    holder_num = Column("holder_num", Integer, nullable=True, comment="股东总户数(A+B)")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(StkHoldernumber.__table__, "engine", engines.ReplacingMergeTree(order_by=StkHoldernumber.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    StkHoldernumber.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(StkHoldernumber.__primary_key__),
            "order_by": ",".join(StkHoldernumber.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    StkHoldernumber.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": StkHoldernumber.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    StkHoldernumber.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": StkHoldernumber.__primary_key__,
        }
    )
except Exception:
    pass
