# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class StockSt(Base):
    """ST股票列表"""

    __tablename__: str = "stock_st"
    __api_id__: ClassVar[int] = 397
    __api_name__: ClassVar[str] = "stock_st"
    __api_title__: ClassVar[str] = "ST股票列表"
    __api_info_title__: ClassVar[str] = "ST股票列表"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "基础数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 3]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = "2016-01-01"
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "股票代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期（格式：YYYYMMDD下同）"},
        "type": {"type": "String", "required": False, "description": "类型"},
        "start_date": {"type": "String", "required": False, "description": "开始时间"},
        "end_date": {"type": "String", "required": False, "description": "结束时间"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "ST股票列表",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="股票代码")
    name = Column("name", String(), nullable=True, comment="股票名称")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    type = Column("type", String(), nullable=True, comment="类型")
    type_name = Column("type_name", String(), nullable=True, comment="类型名称")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(StockSt.__table__, "engine", engines.ReplacingMergeTree(order_by=StockSt.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    StockSt.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(StockSt.__primary_key__),
            "order_by": ",".join(StockSt.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    StockSt.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": StockSt.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    StockSt.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": StockSt.__primary_key__,
        }
    )
except Exception:
    pass
