# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class StockBasic(Base):
    """股票列表"""

    __tablename__: str = "stock_basic"
    __api_id__: ClassVar[int] = 25
    __api_name__: ClassVar[str] = "stock_basic"
    __api_title__: ClassVar[str] = "股票列表"
    __api_info_title__: ClassVar[str] = "股票列表"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "基础数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 3]
    __api_points_required__: ClassVar[int] = 2000
    __api_special_permission__: ClassVar[bool] = True
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "TS股票代码"},
        "name": {"type": "String", "required": False, "description": "名称"},
        "exchange": {"type": "String", "required": False, "description": "交易所 SSE上交所 SZSE深交所 HKEX港交所"},
        "market": {"type": "String", "required": False, "description": "市场类别"},
        "is_hs": {"type": "String", "required": False, "description": "是否沪深港通标的，N否 H沪股通 S深股通"},
        "list_status": {"type": "String", "required": False, "description": "上市状态 L上市 D退市 P暂停上市"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "股票列表",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="TS代码")
    symbol = Column("symbol", String(), nullable=True, comment="股票代码")
    name = Column("name", String(), nullable=True, comment="股票名称")
    area = Column("area", String(), nullable=True, comment="地域")
    industry = Column("industry", String(), nullable=True, comment="所属行业")
    fullname = Column("fullname", String(), nullable=True, comment="股票全称")
    enname = Column("enname", String(), nullable=True, comment="英文全称")
    cnspell = Column("cnspell", String(), nullable=True, comment="拼音缩写")
    market = Column("market", String(), nullable=True, comment="市场类型")
    exchange = Column("exchange", String(), nullable=True, comment="交易所代码")
    curr_type = Column("curr_type", String(), nullable=True, comment="交易货币")
    list_status = Column("list_status", String(), nullable=True, comment="上市状态 L上市 D退市 P暂停上市")
    list_date = Column("list_date", Date, nullable=True, comment="上市日期")
    delist_date = Column("delist_date", Date, nullable=True, comment="退市日期")
    is_hs = Column("is_hs", String(), nullable=True, comment="是否沪深港通标的，N否 H沪股通 S深股通")
    act_name = Column("act_name", String(), nullable=True, comment="实控人名称")
    act_ent_type = Column("act_ent_type", String(), nullable=True, comment="实控人企业性质")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(StockBasic.__table__, "engine", engines.ReplacingMergeTree(order_by=StockBasic.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    StockBasic.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(StockBasic.__primary_key__),
            "order_by": ",".join(StockBasic.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    StockBasic.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": StockBasic.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    StockBasic.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": StockBasic.__primary_key__,
        }
    )
except Exception:
    pass
