# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class SzDailyInfo(Base):
    """深圳市场每日交易情况"""

    __tablename__: str = "sz_daily_info"
    __api_id__: ClassVar[int] = 268
    __api_name__: ClassVar[str] = "sz_daily_info"
    __api_title__: ClassVar[str] = "深圳市场每日交易情况"
    __api_info_title__: ClassVar[str] = "深圳市场每日交易情况"
    __api_path__: ClassVar[List[str]] = ["数据接口", "指数专题"]
    __api_path_ids__: ClassVar[List[int]] = [1, 12]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "ts_code": {"type": "String", "required": False, "description": "板块代码"},
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "深圳市场每日交易情况",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="")
    ts_code = Column("ts_code", String(16), nullable=False, comment="市场类型")
    count = Column("count", Integer, nullable=True, comment="股票个数")
    amount = Column("amount", Float, nullable=True, comment="成交金额")
    vol = Column("vol", String(), nullable=True, comment="成交量")
    total_share = Column("total_share", Float, nullable=True, comment="总股本")
    total_mv = Column("total_mv", Float, nullable=True, comment="总市值")
    float_share = Column("float_share", Float, nullable=True, comment="流通股票")
    float_mv = Column("float_mv", Float, nullable=True, comment="流通市值")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(SzDailyInfo.__table__, "engine", engines.ReplacingMergeTree(order_by=SzDailyInfo.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    SzDailyInfo.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(SzDailyInfo.__primary_key__),
            "order_by": ",".join(SzDailyInfo.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    SzDailyInfo.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": SzDailyInfo.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    SzDailyInfo.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": SzDailyInfo.__primary_key__,
        }
    )
except Exception:
    pass
