# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class TdxMember(Base):
    """通达信板块成分"""

    __tablename__: str = "tdx_member"
    __api_id__: ClassVar[int] = 377
    __api_name__: ClassVar[str] = "tdx_member"
    __api_title__: ClassVar[str] = "通达信板块成分"
    __api_info_title__: ClassVar[str] = "通达信板块成分"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "打板专题数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 10]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal", "tdx_index"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "trade_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "板块代码"},
        "trade_date": {"type": "String", "required": False, "description": "交易日期"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "通达信板块成分",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="板块代码")
    trade_date = Column("trade_date", Date, nullable=False, comment="交易日期")
    con_code = Column("con_code", String(), nullable=True, comment="成分股票代码")
    con_name = Column("con_name", String(), nullable=True, comment="成分股票名称")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(TdxMember.__table__, "engine", engines.ReplacingMergeTree(order_by=TdxMember.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    TdxMember.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(TdxMember.__primary_key__),
            "order_by": ",".join(TdxMember.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    TdxMember.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": TdxMember.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    TdxMember.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": TdxMember.__primary_key__,
        }
    )
except Exception:
    pass
