# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class TeleplayRecord(Base):
    """全国电视剧备案公示数据"""

    __tablename__: str = "teleplay_record"
    __api_id__: ClassVar[int] = 180
    __api_name__: ClassVar[str] = "teleplay_record"
    __api_title__: ClassVar[str] = "全国电视剧备案公示数据"
    __api_info_title__: ClassVar[str] = "全国电视剧备案公示数据"
    __api_path__: ClassVar[List[str]] = ["数据接口", "行业经济", "TMT行业"]
    __api_path_ids__: ClassVar[List[int]] = [1, 21, 22]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["license_key"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "report_date": {"type": "String", "required": False, "description": "备案月份"},
        "start_date": {"type": "String", "required": False, "description": "备案开始月份（YYYYMM）"},
        "end_date": {"type": "String", "required": False, "description": "备案结束月份（YYYYMM）"},
        "org": {"type": "String", "required": False, "description": "备案机构"},
        "name": {"type": "String", "required": False, "description": "电视剧名称"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "全国电视剧备案公示数据",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    name = Column("name", String(), nullable=True, comment="电视剧名称")
    classify = Column("classify", String(), nullable=True, comment="题材")
    types = Column("types", String(), nullable=True, comment="体裁")
    org = Column("org", String(), nullable=True, comment="报备机构")
    report_date = Column("report_date", Date, nullable=True, comment="报备时间")
    license_key = Column("license_key", String(), nullable=False, comment="许可证号")
    episodes = Column("episodes", String(), nullable=True, comment="集数")
    shooting_date = Column("shooting_date", Date, nullable=True, comment="拍摄时间")
    prod_cycle = Column("prod_cycle", String(), nullable=True, comment="制作周期")
    content = Column("content", String(), nullable=True, comment="内容提要")
    pro_opi = Column("pro_opi", String(), nullable=True, comment="省级管理部门备案意见")
    dept_opi = Column("dept_opi", String(), nullable=True, comment="相关部门意见")
    remarks = Column("remarks", String(), nullable=True, comment="备注")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(TeleplayRecord.__table__, "engine", engines.ReplacingMergeTree(order_by=TeleplayRecord.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    TeleplayRecord.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(TeleplayRecord.__primary_key__),
            "order_by": ",".join(TeleplayRecord.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    TeleplayRecord.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": TeleplayRecord.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    TeleplayRecord.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": TeleplayRecord.__primary_key__,
        }
    )
except Exception:
    pass
