# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class ThsIndex(Base):
    """同花顺行业概念板块"""

    __tablename__: str = "ths_index"
    __api_id__: ClassVar[int] = 259
    __api_name__: ClassVar[str] = "ths_index"
    __api_title__: ClassVar[str] = "同花顺行业概念板块"
    __api_info_title__: ClassVar[str] = "同花顺行业概念板块"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "打板专题数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 10]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["ts_code"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "指数代码"},
        "exchange": {"type": "String", "required": False, "description": "市场类型A-a股票 HK-港股 US-美股"},
        "type": {"type": "String", "required": False, "description": "指数类型 N-板块指数 S-同花顺特色指数"},
        "name": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "同花顺行业概念板块",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="代码")
    name = Column("name", String(), nullable=True, comment="名称")
    count = Column("count", Integer, nullable=True, comment="成分个数")
    exchange = Column("exchange", String(), nullable=True, comment="交易所")
    list_date = Column("list_date", Date, nullable=True, comment="上市日期")
    type = Column("type", String(), nullable=True, comment="N概念指数S特色指数")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(ThsIndex.__table__, "engine", engines.ReplacingMergeTree(order_by=ThsIndex.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    ThsIndex.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(ThsIndex.__primary_key__),
            "order_by": ",".join(ThsIndex.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    ThsIndex.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": ThsIndex.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    ThsIndex.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": ThsIndex.__primary_key__,
        }
    )
except Exception:
    pass
