# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class ThsMember(Base):
    """同花顺行业概念成分"""

    __tablename__: str = "ths_member"
    __api_id__: ClassVar[int] = 261
    __api_name__: ClassVar[str] = "ths_member"
    __api_title__: ClassVar[str] = "同花顺行业概念成分"
    __api_info_title__: ClassVar[str] = "同花顺行业概念成分"
    __api_path__: ClassVar[List[str]] = ["数据接口", "股票数据", "打板专题数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 2, 10]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = ["trade_cal", "ths_index"]
    __primary_key__: ClassVar[List[str]] = ["ts_code", "con_code", "in_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "ts_code": {"type": "String", "required": False, "description": "板块指数代码"},
        "con_code": {"type": "String", "required": False, "description": "股票代码"},
        "offset": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "同花顺行业概念成分",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    ts_code = Column("ts_code", String(16), nullable=False, comment="指数代码")
    con_code = Column("con_code", String(), nullable=False, comment="股票代码")
    con_name = Column("con_name", String(), nullable=True, comment="股票名称")
    weight = Column("weight", Float, nullable=True, comment="权重")
    in_date = Column("in_date", Date, nullable=False, comment="纳入日期")
    out_date = Column("out_date", Date, nullable=True, comment="剔除日期")
    is_new = Column("is_new", String(), nullable=True, comment="是否最新Y是N否")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(ThsMember.__table__, "engine", engines.ReplacingMergeTree(order_by=ThsMember.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    ThsMember.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(ThsMember.__primary_key__),
            "order_by": ",".join(ThsMember.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    ThsMember.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": ThsMember.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    ThsMember.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": ThsMember.__primary_key__,
        }
    )
except Exception:
    pass
