# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class TradeCal(Base):
    """交易日历"""

    __tablename__: str = "trade_cal"
    __api_id__: ClassVar[int] = 137
    __api_name__: ClassVar[str] = "trade_cal"
    __api_title__: ClassVar[str] = "交易日历"
    __api_info_title__: ClassVar[str] = "交易日历"
    __api_path__: ClassVar[List[str]] = ["数据接口", "期货数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 14]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["exchange", "cal_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "exchange": {"type": "String", "required": False, "description": "交易所 SSE上交所 SZSE深交所"},
        "cal_date": {"type": "String", "required": False, "description": "日历日期"},
        "start_date": {"type": "String", "required": False, "description": ""},
        "end_date": {"type": "String", "required": False, "description": ""},
        "is_open": {"type": "String", "required": False, "description": "是否交易 0休市 1交易"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "交易日历",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    exchange = Column("exchange", String(), nullable=False, comment="交易所 SSE上交所 SZSE深交所")
    cal_date = Column("cal_date", Date, nullable=False, comment="日历日期")
    is_open = Column("is_open", String(), nullable=True, comment="是否交易 0休市 1交易")
    pretrade_date = Column("pretrade_date", Date, nullable=True, comment="上一个交易日")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(TradeCal.__table__, "engine", engines.ReplacingMergeTree(order_by=TradeCal.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    TradeCal.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(TradeCal.__primary_key__),
            "order_by": ",".join(TradeCal.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    TradeCal.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": TradeCal.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    TradeCal.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": TradeCal.__primary_key__,
        }
    )
except Exception:
    pass
