# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class UbindexConstituents(Base):
    """优币指数成分"""

    __tablename__: str = "ubindex_constituents"
    __api_id__: ClassVar[int] = 99
    __api_name__: ClassVar[str] = "ubindex_constituents"
    __api_title__: ClassVar[str] = "优币指数成分"
    __api_info_title__: ClassVar[str] = "优币指数成分"
    __api_path__: ClassVar[List[str]] = ["另类数据", "行情数据"]
    __api_path_ids__: ClassVar[List[int]] = [37, 39]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["trade_date", "index_name", "symbol"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "index_name": {"type": "String", "required": True, "description": "指数名称"},
        "start_date": {"type": "String", "required": True, "description": "开始日期，格式：yyyymmdd"},
        "end_date": {"type": "String", "required": True, "description": "结束日期，格式：yyyymmdd"},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "优币指数成分",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    trade_date = Column("trade_date", Date, nullable=False, comment="日期")
    index_name = Column("index_name", String(), nullable=False, comment="指数名称")
    symbol = Column("symbol", String(), nullable=False, comment="成分货币简称")
    circulated_cap = Column("circulated_cap", Float, nullable=True, comment="计算周期内日流动市值均值")
    sqrt_cap = Column("sqrt_cap", Float, nullable=True, comment="计算周期内日流动市值均值平方根")
    weight = Column("weight", Float, nullable=True, comment="计算周期内权重")
    price = Column("price", Float, nullable=True, comment="指数日价格")
    create_time = Column("create_time", DateTime, nullable=True, comment="入库时间")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(
        UbindexConstituents.__table__,
        "engine",
        engines.ReplacingMergeTree(order_by=UbindexConstituents.__primary_key__),
    )
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    UbindexConstituents.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(UbindexConstituents.__primary_key__),
            "order_by": ",".join(UbindexConstituents.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    UbindexConstituents.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": UbindexConstituents.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    UbindexConstituents.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": UbindexConstituents.__primary_key__,
        }
    )
except Exception:
    pass
