# This file is auto-generated by generate_models.py
# This file may be manually edited after generation
# The file has been formatted using isort and black

from typing import Any, ClassVar, Dict, List

from sqlalchemy import Column, PrimaryKeyConstraint, text

from tushare_models.core import Base, Date, DateTime, Float, Integer, String


class UsTradecal(Base):
    """美股交易日历"""

    __tablename__: str = "us_tradecal"
    __api_id__: ClassVar[int] = 253
    __api_name__: ClassVar[str] = "us_tradecal"
    __api_title__: ClassVar[str] = "美股交易日历"
    __api_info_title__: ClassVar[str] = "美股交易日历"
    __api_path__: ClassVar[List[str]] = ["数据接口", "美股数据"]
    __api_path_ids__: ClassVar[List[int]] = [1, 20]
    __api_points_required__: ClassVar[int] = 0
    __api_special_permission__: ClassVar[bool] = False
    __has_vip__: ClassVar[bool] = False
    __dependencies__: ClassVar[List[str]] = []
    __primary_key__: ClassVar[List[str]] = ["cal_date"]
    __start_date__: ClassVar[str | None] = None
    __end_date__: ClassVar[str | None] = None
    __api_params__: ClassVar[Dict[str, Any]] = {
        "start_date": {"type": "String", "required": False, "description": "开始日期"},
        "end_date": {"type": "String", "required": False, "description": "结束日期"},
        "is_open": {"type": "String", "required": False, "description": "是否交易 '0'休市 '1'交易"},
        "exchange": {"type": "String", "required": False, "description": ""},
        "limit": {"type": "Int64", "required": False, "description": "单次返回数据长度"},
        "offset": {"type": "Int64", "required": False, "description": "请求数据的开始位移量"},
    }

    __mapper_args__ = {"primary_key": __primary_key__}
    __table_args__ = (
        PrimaryKeyConstraint(*__primary_key__),
        {
            "comment": "美股交易日历",
            # MySQL引擎
            "mysql_engine": "InnoDB",
        },
    )

    cal_date = Column("cal_date", Date, nullable=False, comment="日历日期")
    is_open = Column("is_open", Integer, nullable=True, comment="是否交易 '0'休市 '1'交易")
    pretrade_date = Column("pretrade_date", Date, nullable=True, comment="上一个交易日")


# ClickHouse引擎配置
try:
    from clickhouse_sqlalchemy import engines

    setattr(UsTradecal.__table__, "engine", engines.ReplacingMergeTree(order_by=UsTradecal.__primary_key__))
except Exception:
    pass


# StarRocks引擎配置
try:
    from tushare_models.core.dialect import TSStarRocksDDLCompiler

    UsTradecal.__table__.dialect_options["starrocks"].update(  # type: ignore
        {
            "primary_key": ",".join(UsTradecal.__primary_key__),
            "order_by": ",".join(UsTradecal.__primary_key__),
        }
    )
except Exception:
    pass


# Databend引擎配置
try:
    from tushare_models.core.dialect import TSDatabendDDLCompiler

    UsTradecal.__table__.dialect_options["databend"].update(  # type: ignore
        {
            "cluster_by": UsTradecal.__primary_key__,
        }
    )
except Exception:
    pass


# Doris引擎配置
try:
    UsTradecal.__table__.dialect_options["doris"].update(  # type: ignore
        {
            "unique_key": UsTradecal.__primary_key__,
        }
    )
except Exception:
    pass
